// Auto-generated from snake_dot.asm - do not edit by hand
#pragma once

static const char snake_src[] =
    "; =============================================================================\n"
    "; SNAKE for ABC80  —  dot-graphics version (thin single-dot snake)\n"
    "; =============================================================================\n"
    ";\n"
    "; The ABC80 screen is 40 cols x 24 rows of character cells (7C00h-7FFFh,\n"
    "; non-linear layout — see ROWTAB below).\n"
    ";\n"
    "; Each cell holds a 2x3 grid of addressable \"dots\".\n"
    "; ABC80 mosaic encoding in screen RAM (encoding verified by disassembling the\n"
    "; ABC80 ROM at 22C5h; SETDOT/CLRDOT below are reimplemented from scratch —\n"
    "; the ROM versions use RST 38h to evaluate BASIC expressions and cannot be\n"
    "; called from standalone Z80 code):\n"
    ";\n"
    ";   bit7 = TR (top-right)    bit6 = TL (top-left)\n"
    ";   bit5 = 1  (graphics flag, always set in any mosaic cell)\n"
    ";   bit3 = BR (bot-right)    bit2 = BL (bot-left)\n"
    ";   bit1 = MR (mid-right)    bit0 = ML (mid-left)\n"
    ";\n"
    "; Screen-byte constants used by this game:\n"
    ";\n"
    ";   0EFh (11101111b) — full 2x3 block                       — walls\n"
    ";   021h (00100001b) — ML dot only (center-left)             — snake body\n"
    ";   0A0h (10100000b) — TR dot only (top-right)               — food pellet\n"
    ";   020h (00100000b) — blank (graphics flag only)            — empty cell\n"
    ";\n"
    "; The snake is a thin trail of single center-left dots.\n"
    "; Food is a single pixel in the top-right corner of its cell.\n"
    "; These two are visually distinct and much smaller than a full block.\n"
    ";\n"
    "; COLLISION DETECTION\n"
    ";   GETCHR reads the raw screen byte:\n"
    ";     FOOD_BYTE (0A0h) -> eat pellet\n"
    ";     BLANK     (020h) -> normal move\n"
    ";     anything else    -> wall or self-hit -> GAME OVER\n"
    ";\n"
    "; DRAWING SUBROUTINES\n"
    ";   DRAWSEG  (B=row, C=col) — SETDOT at ML (col*2, row*3+1)\n"
    ";   ERASESEG (B=row, C=col) — CLRDOT at ML (col*2, row*3+1)\n"
    ";   DRAWFOOD (B=row, C=col) — SETDOT at TR (col*2+1, row*3)\n"
    ";\n"
    "; SCREEN LAYOUT  (col 0 always holds 97h — graphics-mode marker)\n"
    ";\n"
    ";   Row  0        top wall     (full blocks, cols 1-39)\n"
    ";   Rows 1-22     play field\n"
    ";   Row  23       bottom wall  (full blocks, cols 1-39)\n"
    ";   Col  1        left wall    (full blocks, rows 1-22)\n"
    ";   Col  39       right wall   (full blocks, rows 1-22)\n"
    ";   Cols 2-38     play area    (37 cols x 22 rows)\n"
    ";\n"
    "; CONTROLS   W=up  S=down  A=left  D=right  (upper or lower case)\n"
    ";            Ctrl-C = quit\n"
    ";\n"
    "; HOW TO RUN FROM THE MONITOR\n"
    ";   AS 8000   assemble at 8000h\n"
    ";   G 8000    run\n"
    "; =============================================================================\n"
    "\n"
    "; ---------------------------------------------------------------------------\n"
    "; Game variables  (8F00h — well above the assembled code)\n"
    "; ---------------------------------------------------------------------------\n"
    "\n"
    "SHEAD   EQU 08F00H  ; ring-buffer head index  (0-63, wraps with AND 3Fh)\n"
    "STAIL   EQU 08F01H  ; ring-buffer tail index  (0-63)\n"
    "DIR     EQU 08F02H  ; current direction: 0=right 1=down 2=left 3=up\n"
    "NDIR    EQU 08F03H  ; next (pending) direction from keyboard\n"
    "PCLK    EQU 08F04H  ; previous 50 Hz clock byte\n"
    "SPEED   EQU 08F05H  ; frame counter — move tick every 4th frame\n"
    "RNG     EQU 08F06H  ; Galois LFSR state\n"
    "KEY     EQU 08F07H  ; ASCII of last key (bit 7 stripped)\n"
    "PFROW   EQU 08F08H  ; food-placement scratch: candidate row\n"
    "PFCOL   EQU 08F09H  ; food-placement scratch: candidate col\n"
    "\n"
    "; ---------------------------------------------------------------------------\n"
    "; Ring buffer  (9000h, 64 entries x 2 bytes = 128 bytes)\n"
    "; ---------------------------------------------------------------------------\n"
    "\n"
    "SBUF    EQU 09000H\n"
    "SMASK   EQU 03FH\n"
    "\n"
    "; ---------------------------------------------------------------------------\n"
    "; Hardware\n"
    "; ---------------------------------------------------------------------------\n"
    "\n"
    "CLKLO   EQU 0FDF0H  ; 50 Hz real-time clock low byte\n"
    "\n"
    "; ---------------------------------------------------------------------------\n"
    "; Screen-byte constants  (correct ABC80 mosaic encoding)\n"
    "; ---------------------------------------------------------------------------\n"
    "\n"
    "BLOCK_BYTE  EQU 0EFH    ; 11101111b — walls: all 6 dots + flag\n"
    "SNAKE_BYTE  EQU 021H    ; 00100001b — snake body: ML dot + flag\n"
    "FOOD_BYTE   EQU 0A0H    ; 10100000b — food: TR dot + flag\n"
    "BLANK       EQU 020H    ; 00100000b — empty: graphics flag only\n"
    "GFXMK       EQU 097H    ; CHR$(151) in col 0 — switches row to graphics mode\n"
    "\n"
    "; ---------------------------------------------------------------------------\n"
    "; Direction constants\n"
    "; ---------------------------------------------------------------------------\n"
    "\n"
    "DRIGHT  EQU 0\n"
    "DDOWN   EQU 1\n"
    "DLEFT   EQU 2\n"
    "DUP     EQU 3\n"
    "\n"
    "; ---------------------------------------------------------------------------\n"
    "        ORG 8000H\n"
    "; ---------------------------------------------------------------------------\n"
    "\n"
    "; =============================================================================\n"
    "; START\n"
    "; =============================================================================\n"
    "START:\n"
    "        DI\n"
    "\n"
    "        CALL INITSCR\n"
    "\n"
    "        LD HL, CLKLO\n"
    "        LD A, (HL)\n"
    "        LD HL, RNG\n"
    "        XOR (HL)                ; seed LFSR from clock ^ existing state\n"
    "        OR A\n"
    "        JR NZ, RSEED_OK\n"
    "        INC A\n"
    "RSEED_OK:\n"
    "        LD (RNG), A\n"
    "\n"
    "        ; Initial snake: 3 segments at row 11, cols 18-20, heading right\n"
    "        XOR A\n"
    "        LD (STAIL), A\n"
    "        LD A, 2\n"
    "        LD (SHEAD), A\n"
    "\n"
    "        LD HL, SBUF\n"
    "        LD (HL), 11\n"
    "        INC HL\n"
    "        LD (HL), 18\n"
    "        INC HL\n"
    "        LD (HL), 11\n"
    "        INC HL\n"
    "        LD (HL), 19\n"
    "        INC HL\n"
    "        LD (HL), 11\n"
    "        INC HL\n"
    "        LD (HL), 20\n"
    "\n"
    "        ; Draw initial snake segments (thin ML dot per cell)\n"
    "        LD B, 11\n"
    "        LD C, 18\n"
    "        CALL DRAWSEG\n"
    "        LD B, 11\n"
    "        LD C, 19\n"
    "        CALL DRAWSEG\n"
    "        LD B, 11\n"
    "        LD C, 20\n"
    "        CALL DRAWSEG\n"
    "\n"
    "        LD A, DRIGHT\n"
    "        LD (DIR), A\n"
    "        LD (NDIR), A\n"
    "\n"
    "        CALL PLACEFOOD\n"
    "\n"
    "        LD A, (CLKLO)\n"
    "        LD (PCLK), A\n"
    "        XOR A\n"
    "        LD (SPEED), A\n"
    "\n"
    "; =============================================================================\n"
    "; MAIN LOOP  (once per 50 Hz tick)\n"
    "; =============================================================================\n"
    "LOOP:\n"
    "        ; --- 1. Wait for next tick ---\n"
    "        LD HL, CLKLO\n"
    "WCLK:   LD A, (PCLK)\n"
    "        CP (HL)\n"
    "        JR Z, WCLK\n"
    "        LD A, (HL)\n"
    "        LD (PCLK), A\n"
    "\n"
    "        ; --- 2. Tick RNG ---\n"
    "        CALL RNGBYTE\n"
    "\n"
    "        ; --- 3. Read keyboard ---\n"
    "        IN A, (038H)\n"
    "        AND 07FH\n"
    "        CP 03H\n"
    "        JP Z, EXIT\n"
    "        AND 05FH\n"
    "        LD (KEY), A\n"
    "\n"
    "        ; --- 4. Update pending direction ---\n"
    "\n"
    "        ; W -> UP\n"
    "        LD A, (KEY)\n"
    "        CP 057H\n"
    "        JR NZ, NOK_U\n"
    "        LD A, (DIR)\n"
    "        CP DDOWN\n"
    "        JR Z, NOK_U\n"
    "        LD A, DUP\n"
    "        LD (NDIR), A\n"
    "NOK_U:\n"
    "        ; S -> DOWN\n"
    "        LD A, (KEY)\n"
    "        CP 053H\n"
    "        JR NZ, NOK_D\n"
    "        LD A, (DIR)\n"
    "        CP DUP\n"
    "        JR Z, NOK_D\n"
    "        LD A, DDOWN\n"
    "        LD (NDIR), A\n"
    "NOK_D:\n"
    "        ; A -> LEFT\n"
    "        LD A, (KEY)\n"
    "        CP 041H\n"
    "        JR NZ, NOK_L\n"
    "        LD A, (DIR)\n"
    "        CP DRIGHT\n"
    "        JR Z, NOK_L\n"
    "        LD A, DLEFT\n"
    "        LD (NDIR), A\n"
    "NOK_L:\n"
    "        ; D -> RIGHT\n"
    "        LD A, (KEY)\n"
    "        CP 044H\n"
    "        JR NZ, NOK_R\n"
    "        LD A, (DIR)\n"
    "        CP DLEFT\n"
    "        JR Z, NOK_R\n"
    "        LD A, DRIGHT\n"
    "        LD (NDIR), A\n"
    "NOK_R:\n"
    "\n"
    "        ; --- 5. Speed throttle: move every 4th tick ---\n"
    "        LD A, (SPEED)\n"
    "        INC A\n"
    "        LD (SPEED), A\n"
    "        AND 03H\n"
    "        JP NZ, LOOP\n"
    "\n"
    "        ; --- 6. Commit direction ---\n"
    "        LD A, (NDIR)\n"
    "        LD (DIR), A\n"
    "\n"
    "        ; --- 7. Fetch head (row, col) from SBUF[SHEAD] ---\n"
    "        LD A, (SHEAD)\n"
    "        ADD A, A\n"
    "        LD L, A\n"
    "        LD H, 090H\n"
    "        LD B, (HL)\n"
    "        INC HL\n"
    "        LD C, (HL)\n"
    "\n"
    "        ; --- 8. Look up direction delta ---\n"
    "        LD A, (DIR)\n"
    "        ADD A, A\n"
    "        LD E, A\n"
    "        LD D, 0\n"
    "        LD HL, DRTAB\n"
    "        ADD HL, DE\n"
    "        LD D, (HL)\n"
    "        INC HL\n"
    "        LD E, (HL)\n"
    "\n"
    "        ; --- 9. Compute new head position ---\n"
    "        LD A, B\n"
    "        ADD A, D\n"
    "        LD B, A\n"
    "        LD A, C\n"
    "        ADD A, E\n"
    "        LD C, A\n"
    "\n"
    "        ; --- 10. Check cell at new head ---\n"
    "        CALL GETCHR             ; A = screen byte at (B, C)\n"
    "\n"
    "        CP FOOD_BYTE            ; 0A0h — food?\n"
    "        JR Z, EATFOOD\n"
    "\n"
    "        CP BLANK                ; 020h — empty cell?\n"
    "        JP NZ, GAMEOVER         ; anything else: wall (0EFh) or self (021h)\n"
    "\n"
    "        ; --- 11. Normal move ---\n"
    "\n"
    "        ; a) Fetch tail (row, col) from SBUF[STAIL]\n"
    "        LD A, (STAIL)\n"
    "        ADD A, A\n"
    "        LD L, A\n"
    "        LD H, 090H\n"
    "        LD D, (HL)\n"
    "        INC HL\n"
    "        LD E, (HL)\n"
    "\n"
    "        ; b) Erase tail dot (CLRDOT → cell returns to BLANK)\n"
    "        PUSH BC\n"
    "        LD B, D\n"
    "        LD C, E\n"
    "        CALL ERASESEG\n"
    "        POP BC\n"
    "\n"
    "        ; c) Advance STAIL\n"
    "        LD A, (STAIL)\n"
    "        INC A\n"
    "        AND SMASK\n"
    "        LD (STAIL), A\n"
    "\n"
    "        ; d) Advance SHEAD, store new head\n"
    "        LD A, (SHEAD)\n"
    "        INC A\n"
    "        AND SMASK\n"
    "        LD (SHEAD), A\n"
    "        ADD A, A\n"
    "        LD L, A\n"
    "        LD H, 090H\n"
    "        LD (HL), B\n"
    "        INC HL\n"
    "        LD (HL), C\n"
    "\n"
    "        ; e) Draw new head as thin snake dot\n"
    "        CALL DRAWSEG\n"
    "\n"
    "        JP LOOP\n"
    "\n"
    "; =============================================================================\n"
    "; EATFOOD — grow snake by one, place new food\n"
    "; =============================================================================\n"
    "EATFOOD:\n"
    "        ; Advance SHEAD, store new head (no tail erase — snake grows)\n"
    "        LD A, (SHEAD)\n"
    "        INC A\n"
    "        AND SMASK\n"
    "        LD (SHEAD), A\n"
    "        ADD A, A\n"
    "        LD L, A\n"
    "        LD H, 090H\n"
    "        LD (HL), B\n"
    "        INC HL\n"
    "        LD (HL), C\n"
    "\n"
    "        ; Write SNAKE_BYTE directly — food cell had TR bit set; PUTCHR\n"
    "        ; clears it cleanly so ERASESEG later sees exactly SNAKE_BYTE (021h).\n"
    "        LD A, SNAKE_BYTE\n"
    "        CALL PUTCHR\n"
    "\n"
    "        CALL PLACEFOOD\n"
    "\n"
    "        JP LOOP\n"
    "\n"
    "; =============================================================================\n"
    "; GAMEOVER  — freeze ~2 s then restart\n"
    "; =============================================================================\n"
    "GAMEOVER:\n"
    "        LD D, 100\n"
    "GOWAIT: LD HL, CLKLO\n"
    "GOWLP:  LD A, (PCLK)\n"
    "        CP (HL)\n"
    "        JR Z, GOWLP\n"
    "        LD A, (HL)\n"
    "        LD (PCLK), A\n"
    "        DEC D\n"
    "        JR NZ, GOWAIT\n"
    "        JP START\n"
    "\n"
    "; =============================================================================\n"
    "; EXIT — re-enable interrupts and return to monitor\n"
    "; =============================================================================\n"
    "EXIT:\n"
    "        EI\n"
    "        RET\n"
    "\n"
    "; =============================================================================\n"
    "; INITSCR — initialise screen for a new game\n"
    ";\n"
    "; 1. Write GFXMK to col 0 and BLANK to cols 1-39 of every row.\n"
    "; 2. Draw walls using PUTCHR with BLOCK_BYTE (full 6-dot cells).\n"
    "; =============================================================================\n"
    "INITSCR:\n"
    "        ; Step 1: GFXMK in col 0, BLANK in cols 1-39 (direct writes, fast)\n"
    "        LD B, 24\n"
    "        LD HL, ROWTAB\n"
    "ILUP:\n"
    "        LD E, (HL)\n"
    "        INC HL\n"
    "        LD D, (HL)\n"
    "        INC HL\n"
    "        PUSH BC\n"
    "        PUSH HL\n"
    "        EX DE, HL\n"
    "        LD (HL), GFXMK\n"
    "        INC HL\n"
    "        LD B, 39\n"
    "ICLR:   LD (HL), BLANK\n"
    "        INC HL\n"
    "        DJNZ ICLR\n"
    "        POP HL\n"
    "        POP BC\n"
    "        DJNZ ILUP\n"
    "\n"
    "        ; Step 2: top wall (row 0, cols 1-39)\n"
    "        ; PUTCHR preserves A, B, C — only D, E, H, L clobbered.\n"
    "        LD B, 0\n"
    "        LD C, 1\n"
    "        LD D, 39\n"
    "        LD A, BLOCK_BYTE\n"
    "ITOP:   PUSH DE\n"
    "        CALL PUTCHR\n"
    "        POP DE\n"
    "        INC C\n"
    "        DEC D\n"
    "        JR NZ, ITOP\n"
    "\n"
    "        ; Step 3: bottom wall (row 23, cols 1-39)\n"
    "        LD B, 23\n"
    "        LD C, 1\n"
    "        LD D, 39\n"
    "        LD A, BLOCK_BYTE\n"
    "IBOT:   PUSH DE\n"
    "        CALL PUTCHR\n"
    "        POP DE\n"
    "        INC C\n"
    "        DEC D\n"
    "        JR NZ, IBOT\n"
    "\n"
    "        ; Step 4: left wall (rows 1-22, col 1)\n"
    "        LD B, 1\n"
    "        LD C, 1\n"
    "        LD D, 22\n"
    "        LD A, BLOCK_BYTE\n"
    "ILFT:   PUSH DE\n"
    "        CALL PUTCHR\n"
    "        POP DE\n"
    "        INC B\n"
    "        DEC D\n"
    "        JR NZ, ILFT\n"
    "\n"
    "        ; Step 5: right wall (rows 1-22, col 39)\n"
    "        LD B, 1\n"
    "        LD C, 39\n"
    "        LD D, 22\n"
    "        LD A, BLOCK_BYTE\n"
    "IRGT:   PUSH DE\n"
    "        CALL PUTCHR\n"
    "        POP DE\n"
    "        INC B\n"
    "        DEC D\n"
    "        JR NZ, IRGT\n"
    "\n"
    "        RET\n"
    "\n"
    "; =============================================================================\n"
    "; PLACEFOOD — place food at a random empty cell in the play area\n"
    "; =============================================================================\n"
    "PLACEFOOD:\n"
    "        LD B, 64\n"
    "PFLOOP:\n"
    "        PUSH BC\n"
    "        CALL RNGBYTE\n"
    "        CALL RNGBYTE\n"
    "        AND 01FH\n"
    "        CP 22\n"
    "        JR C, PFROW_OK\n"
    "        SUB 22\n"
    "PFROW_OK:\n"
    "        INC A\n"
    "        LD (PFROW), A\n"
    "\n"
    "        CALL RNGBYTE\n"
    "        CALL RNGBYTE\n"
    "        AND 03FH\n"
    "        CP 37\n"
    "        JR C, PFCOL_OK\n"
    "        SUB 37\n"
    "PFCOL_OK:\n"
    "        ADD A, 2\n"
    "        LD (PFCOL), A\n"
    "\n"
    "        LD A, (PFROW)\n"
    "        LD B, A\n"
    "        LD A, (PFCOL)\n"
    "        LD C, A\n"
    "        CALL GETCHR\n"
    "        POP BC\n"
    "        CP BLANK\n"
    "        JR NZ, PFNEXT\n"
    "\n"
    "        ; Empty cell found — draw food dot (TR position)\n"
    "        LD A, (PFROW)\n"
    "        LD B, A\n"
    "        LD A, (PFCOL)\n"
    "        LD C, A\n"
    "        CALL DRAWFOOD\n"
    "        RET\n"
    "\n"
    "PFNEXT:\n"
    "        DJNZ PFLOOP\n"
    "        RET\n"
    "\n"
    "; =============================================================================\n"
    "; RNGBYTE — Galois LFSR step, result in A\n"
    "; =============================================================================\n"
    "RNGBYTE:\n"
    "        LD A, (RNG)\n"
    "        RRCA\n"
    "        JR NC, RNGB1\n"
    "        XOR 0B8H\n"
    "RNGB1:  LD (RNG), A\n"
    "        RET\n"
    "\n"
    "; =============================================================================\n"
    "; GETCHR — read screen byte at char cell (B=row, C=col)\n"
    "; Exit: A = screen byte;  B, C preserved\n"
    "; =============================================================================\n"
    "GETCHR:\n"
    "        CALL SCRADDR\n"
    "        LD A, (HL)\n"
    "        RET\n"
    "\n"
    "; =============================================================================\n"
    "; PUTCHR — write A to screen RAM at char cell (B=row, C=col)\n"
    "; Exit: A, B, C preserved\n"
    "; =============================================================================\n"
    "PUTCHR:\n"
    "        PUSH AF\n"
    "        CALL SCRADDR\n"
    "        POP AF\n"
    "        LD (HL), A\n"
    "        RET\n"
    "\n"
    "; =============================================================================\n"
    "; SCRADDR — convert char (row, col) to screen-RAM address\n"
    ";\n"
    "; Entry:  B = row (0-23),  C = col (0-39)\n"
    "; Exit:   HL = screen address;  B, C preserved;  A, D, E clobbered\n"
    "; =============================================================================\n"
    "SCRADDR:\n"
    "        LD HL, ROWTAB\n"
    "        LD A, B\n"
    "        ADD A, A\n"
    "        LD D, 0\n"
    "        LD E, A\n"
    "        ADD HL, DE\n"
    "        LD A, (HL)\n"
    "        INC HL\n"
    "        LD H, (HL)\n"
    "        LD L, A\n"
    "        LD D, 0\n"
    "        LD E, C\n"
    "        ADD HL, DE\n"
    "        RET\n"
    "\n"
    "; =============================================================================\n"
    "; DRAWSEG — draw one snake segment at char cell (B=row, C=col)\n"
    ";\n"
    "; Sets the ML dot (center-left, bit0) at dot coords (col*2, row*3+1).\n"
    "; Cell byte becomes 021h (SNAKE_BYTE) if the cell was BLANK.\n"
    "; B, C preserved.\n"
    "; =============================================================================\n"
    "DRAWSEG:\n"
    "        PUSH BC\n"
    "        LD A, B\n"
    "        ADD A, B\n"
    "        ADD A, B        ; A = row*3\n"
    "        INC A           ; A = row*3+1  (center dot row within cell)\n"
    "        LD B, A\n"
    "        LD A, C\n"
    "        ADD A, C        ; A = col*2  (left dot column)\n"
    "        LD C, A\n"
    "        CALL SETDOT\n"
    "        POP BC\n"
    "        RET\n"
    "\n"
    "; =============================================================================\n"
    "; ERASESEG — erase one snake segment at char cell (B=row, C=col)\n"
    ";\n"
    "; Clears the ML dot (bit0) at dot coords (col*2, row*3+1).\n"
    "; Cell byte returns to 020h (BLANK): bit5 kept, bit0 cleared.\n"
    "; B, C preserved.\n"
    "; =============================================================================\n"
    "ERASESEG:\n"
    "        PUSH BC\n"
    "        LD A, B\n"
    "        ADD A, B\n"
    "        ADD A, B        ; A = row*3\n"
    "        INC A           ; A = row*3+1\n"
    "        LD B, A\n"
    "        LD A, C\n"
    "        ADD A, C        ; A = col*2\n"
    "        LD C, A\n"
    "        CALL CLRDOT\n"
    "        POP BC\n"
    "        RET\n"
    "\n"
    "; =============================================================================\n"
    "; DRAWFOOD — draw food dot at char cell (B=row, C=col)\n"
    ";\n"
    "; Sets the TR dot (top-right, bit7) at dot coords (col*2+1, row*3).\n"
    "; Cell byte becomes 0A0h (FOOD_BYTE) if the cell was BLANK.\n"
    "; B, C preserved.\n"
    "; =============================================================================\n"
    "DRAWFOOD:\n"
    "        PUSH BC\n"
    "        LD A, B\n"
    "        ADD A, B\n"
    "        ADD A, B        ; A = row*3  (top dot row within cell)\n"
    "        LD B, A\n"
    "        LD A, C\n"
    "        ADD A, C\n"
    "        INC A           ; A = col*2+1  (right dot column)\n"
    "        LD C, A\n"
    "        CALL SETDOT\n"
    "        POP BC\n"
    "        RET\n"
    "\n"
    "; =============================================================================\n"
    "; SETDOT — set one dot in screen RAM\n"
    ";\n"
    "; Entry:  C = dot x (0-79),  B = dot y (0-71)\n"
    "; Exit:   dot set;  B, C preserved;  A, D, E, H, L clobbered\n"
    "; =============================================================================\n"
    "SETDOT:\n"
    "        PUSH BC\n"
    "        CALL DOTADDR            ; HL = screen address, A = bit mask; B,C clobbered\n"
    "        OR  (HL)                ; merge dot into current cell byte\n"
    "        OR  020H                ; always ensure graphics flag (bit5)\n"
    "        LD  (HL), A\n"
    "        POP BC\n"
    "        RET\n"
    "\n"
    "; =============================================================================\n"
    "; CLRDOT — clear one dot in screen RAM\n"
    ";\n"
    "; Entry:  C = dot x (0-79),  B = dot y (0-71)\n"
    "; Exit:   dot cleared;  B, C preserved;  A, D, E, H, L clobbered\n"
    "; =============================================================================\n"
    "CLRDOT:\n"
    "        PUSH BC\n"
    "        CALL DOTADDR\n"
    "        CPL                     ; invert mask -> all bits set except our dot\n"
    "        AND (HL)                ; clear the dot bit\n"
    "        OR  020H                ; keep graphics flag\n"
    "        LD  (HL), A\n"
    "        POP BC\n"
    "        RET\n"
    "\n"
    "; =============================================================================\n"
    "; DOTADDR — compute screen address and bit mask for dot (C=x, B=y)\n"
    ";\n"
    "; Entry:  C = dot x (0-79),  B = dot y (0-71)\n"
    "; Exit:   HL = screen-RAM address of the char cell containing this dot\n"
    ";         A  = bit mask (one of: 40h 80h 01h 02h 04h 08h)\n"
    ";         B, C CLOBBERED\n"
    ";\n"
    "; Algorithm:\n"
    ";   char_row = y/3   char_col = x/2\n"
    ";   mask index = (y%3)*2 + (x%2)  ->  DMASK_TAB[index]\n"
    "; =============================================================================\n"
    "DOTADDR:\n"
    "        ; Step 1: compute char_row (B) and y%3 (A)\n"
    "        LD  A, B\n"
    "        LD  B, 0\n"
    "DOTD_Y: CP  3\n"
    "        JR  C, DOTD_YD\n"
    "        SUB 3\n"
    "        INC B\n"
    "        JR  DOTD_Y\n"
    "DOTD_YD:\n"
    "        ; A = y%3,  B = char_row\n"
    "\n"
    "        ; Step 2: mask index = (y%3)*2 + (x%2)\n"
    "        ADD A, A                ; A = (y%3)*2\n"
    "        BIT 0, C\n"
    "        JR  Z, DOTD_EV\n"
    "        INC A\n"
    "DOTD_EV:\n"
    "        ; Step 3: char_col = x/2 -> save in E\n"
    "        LD  E, C\n"
    "        SRL E\n"
    "\n"
    "        ; Step 4: fetch bit mask from DMASK_TAB\n"
    "        PUSH BC\n"
    "        LD  B, 0\n"
    "        LD  C, A\n"
    "        LD  HL, DMASK_TAB\n"
    "        ADD HL, BC\n"
    "        LD  A, (HL)\n"
    "        POP BC\n"
    "\n"
    "        PUSH AF                 ; save bit mask\n"
    "\n"
    "        ; Step 5: row base address from ROWTAB[char_row * 2]\n"
    "        LD  A, B\n"
    "        ADD A, A\n"
    "        LD  C, A\n"
    "        LD  B, 0\n"
    "        LD  HL, ROWTAB\n"
    "        ADD HL, BC\n"
    "        LD  A, (HL)\n"
    "        INC HL\n"
    "        LD  H, (HL)\n"
    "        LD  L, A\n"
    "\n"
    "        ; Step 6: add char_col\n"
    "        LD  D, 0\n"
    "        ADD HL, DE\n"
    "\n"
    "        POP AF                  ; A = bit mask\n"
    "        RET\n"
    "\n"
    "; =============================================================================\n"
    "; DMASK_TAB — dot bit-mask lookup (6 bytes)\n"
    ";\n"
    "; Index = (y%3)*2 + (x%2):\n"
    ";   0  TL bit6   1  TR bit7\n"
    ";   2  ML bit0   3  MR bit1\n"
    ";   4  BL bit2   5  BR bit3\n"
    "; =============================================================================\n"
    "DMASK_TAB:\n"
    "        DEFB 040H, 080H         ; y%3=0: TL (bit6),  TR (bit7)\n"
    "        DEFB 001H, 002H         ; y%3=1: ML (bit0),  MR (bit1)\n"
    "        DEFB 004H, 008H         ; y%3=2: BL (bit2),  BR (bit3)\n"
    "\n"
    "; =============================================================================\n"
    "; DRTAB — direction delta table  (drow, dcol)\n"
    "; =============================================================================\n"
    "DRTAB:\n"
    "        DEFB 0,    1            ; DRIGHT\n"
    "        DEFB 1,    0            ; DDOWN\n"
    "        DEFB 0,  0FFH           ; DLEFT\n"
    "        DEFB 0FFH, 0            ; DUP\n"
    "\n"
    "; =============================================================================\n"
    "; ROWTAB — screen-RAM start address for each of the 24 rows (little-endian)\n"
    "; =============================================================================\n"
    "ROWTAB:\n"
    "        DW 07C00H               ; row  0\n"
    "        DW 07C80H               ; row  1\n"
    "        DW 07D00H               ; row  2\n"
    "        DW 07D80H               ; row  3\n"
    "        DW 07E00H               ; row  4\n"
    "        DW 07E80H               ; row  5\n"
    "        DW 07F00H               ; row  6\n"
    "        DW 07F80H               ; row  7\n"
    "        DW 07C28H               ; row  8\n"
    "        DW 07CA8H               ; row  9\n"
    "        DW 07D28H               ; row 10\n"
    "        DW 07DA8H               ; row 11\n"
    "        DW 07E28H               ; row 12\n"
    "        DW 07EA8H               ; row 13\n"
    "        DW 07F28H               ; row 14\n"
    "        DW 07FA8H               ; row 15\n"
    "        DW 07C50H               ; row 16\n"
    "        DW 07CD0H               ; row 17\n"
    "        DW 07D50H               ; row 18\n"
    "        DW 07DD0H               ; row 19\n"
    "        DW 07E50H               ; row 20\n"
    "        DW 07ED0H               ; row 21\n"
    "        DW 07F50H               ; row 22\n"
    "        DW 07FD0H               ; row 23\n"
    ;
