#define _DEFAULT_SOURCE
// ABC80 emulator
// This emulator has only been tested on macOS with ncurses installed.
// There are here many different ways of interacting with the BASIC
// interpreter. Many of them either intercepts commands from the
// terminal keyboard, before they reach the interpreter. Others catch
// the output buffers before they reach the screen. Another is to fake
// a device to grab the listing of a program for saving.
// Emulation is not pretty, but somehow it just may work.

#include <stdio.h>
#include <string.h>
#include <dirent.h>
#include <stdint.h>
#include <stdbool.h>
#include <locale.h>
#include <signal.h>
#include <unistd.h>
#include <time.h>
#include <ncurses.h>

#include "abcprom.h"
#include "z80.h"

//   ABC80 uses a Swedish variant of 7-bit ASCII (SIS 662241) (SIS 63 61 27)
//   Some positions that differ from standard ASCII are:
//
//   0x24 = ¤    "sol-symbol" ($ in ASCII)
//   0x5B = Ä    0x5C = Ö    0x5D = Å
//   0x7B = ä    0x7C = ö    0x7D = å
//   0x5E = Ü    0x7E = ü
//   0x60 = é
//
//   Input arrives in two flavours depending on how the terminal is configured:
//
//   Direct UTF-8 (Option-as-character mode, default on macOS Terminal)
//   Sorry, you might have to change this if not a macOS is used:
//     The special character is sent as a raw multi-byte UTF-8 sequence.
//     We catch the lead byte (0xC2 or 0xC3) and immediately read the
//     continuation byte from the same getch() call.
//
//   Meta/ESC prefix (Option-as-Meta mode, or pressing Option then key):
//     The terminal sends 0x1B followed by a second byte.  We must NOT
//     treat every 0x1B as "quit" -- instead we cache the ESC in
//     esc_pending and resolve it on the very next read_key() call:
//       ESC with no follow-up  --> bare ESC key --> quit
//       ESC + '4'              --> ¤  (0x24)
//       ESC + 'e' / 'E'        --> é  (0x60)
//       ESC + 'u' / 'U'        --> ü  (0x7E)
//       ESC + anything else    --> silently ignored

// Screen RAM: 24 rows × 40 cols, non-linear layout.
// The hardware interleaves rows in banks of 8, each row 0x28 bytes apart.
// rowstart[r] = base address of row r in the Z80 address space.
static const uint16_t rowstart[24] = {
    0x7C00, 0x7C80, 0x7D00, 0x7D80, 0x7E00, 0x7E80, 0x7F00, 0x7F80,
    0x7C28, 0x7CA8, 0x7D28, 0x7DA8, 0x7E28, 0x7EA8, 0x7F28, 0x7FA8,
    0x7C50, 0x7CD0, 0x7D50, 0x7DD0, 0x7E50, 0x7ED0, 0x7F50, 0x7FD0
};

// PIO port A (keyboard), interrupt vector, PIO port B (B serial bus).
// The keyboard strobe is generated by the hardware at 50 Hz; we simulate
// it with a software timer.  Without the strobe the BASIC input loop
// does not advance and the screen scrolls uncontrolled.
#define KB_PORT          0x38   // IN A,(0x38) reads pending keycode
#define KB_INT_VEC       0x34   // interrupt vector delivered to Z80
#define B_PORT         0x3A   // IN A,(0x3A) - idle bus: all lines high

#define STROBE_HZ        50
#define STEPS_PER_STROBE (3000000 / STROBE_HZ)   // ~60 000 steps per strobe
#define STEPS_PER_REFRESH 5000                   // ncurses refresh interval

// Keyboard state.
// pending_key holds the ABC80 keycode (bit 7 set) waiting to be read.
// key_reads counts how many more port reads will return it (always 2).
static uint8_t pending_key = 0;
static int     key_reads   = 0;
static bool    done        = false;

// ELIST capture state.
// list_out is non-NULL while a listing is being captured to a .BAS file.
// The capture hooks intercept the ROM's device-output CALL at PC=0x0B74.
static FILE *list_out = NULL;

// ETEXT inject state.
// We feed each text line back to BASIC one character at a time, exactly
// as if the user had typed it.  BASIC's keyboard ISR echoes each char,
// builds m[0xFE40], and tokenises the line on the final CR — same path
// as real keyboard input, so no tokenizer hacks are needed.
static FILE    *etext_file = NULL;
static uint8_t  etext_buf[128];  // current line translated to ABC80 codes
static int      etext_pos  = 0;  // index of next char to inject
static int      etext_len  = 0;  // total chars in etext_buf (incl. CR)
static int      etext_delay = 0; // countdown steps before next injection
#define ETEXT_LINE_DELAY 100000  // ~33 ms: time for BASIC to tokenise+store

// Emulator status string displayed in the info bar below the screen.
// Updated by file operations and key emulator events.
static char emul_status[80] = "STARTING";

// Running total of executed Z80 instructions (for the info display).
static long long total_steps = 0;


static long long now_ns(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (long long) ts.tv_sec * 1000000000LL + ts.tv_nsec;
}



// CHAR TRANSLATION

// Convert a 2-byte UTF-8 sequence to an ABC80 character code.
// lead must be 0xC2 or 0xC3 (covers U+0080..U+00FF);
// cont is the continuation byte.
// Returns the ABC80 SIS-662241 code, or 0 if the pair is not a
// recognised Swedish/ABC80 character.
static uint8_t utf8_to_abc80_char(unsigned char lead, unsigned char cont) {
    if (lead == 0xC2) {
        return (cont == 0xA4) ? 0x24 : 0;   // ¤  U+00A4
    }
    if (lead == 0xC3) {
        switch (cont) {
            case 0xA4: return 0x7B;  // ä  U+00E4
            case 0xB6: return 0x7C;  // ö  U+00F6
            case 0xA5: return 0x7D;  // å  U+00E5
            case 0x84: return 0x5B;  // Ä  U+00C4
            case 0x96: return 0x5C;  // Ö  U+00D6
            case 0x85: return 0x5D;  // Å  U+00C5
            case 0xA9: return 0x60;  // é  U+00E9
            case 0x9C: return 0x5E;  // Ü  U+00DC
            case 0xBC: return 0x7E;  // ü  U+00FC
            default:   return 0;
        }
    }
    return 0;
}

// Map ABC80 character codes to printable UTF-8 for screen display.
// The screen RAM stores raw ABC80 codes; we translate on the way out.
// Returns a UTF-8 string literal, or NULL for plain ASCII (use mvaddch).
static const char *abc80_to_utf8(uint8_t c) {
    switch (c & 0x7F) {
        case 0x24: return "\xC2\xA4";  // ¤
        case 0x5B: return "\xC3\x84";  // Ä
        case 0x5C: return "\xC3\x96";  // Ö
        case 0x5D: return "\xC3\x85";  // Å
        case 0x5E: return "\xC3\x9C";  // Ü
        case 0x7B: return "\xC3\xA4";  // ä
        case 0x7C: return "\xC3\xB6";  // ö
        case 0x7D: return "\xC3\xA5";  // å
        case 0x7E: return "\xC3\xBC";  // ü
        case 0x60: return "\xC3\xA9";  // é
        default:   return NULL;        // plain ASCII
    }
}



// KEYBOARD INPUT

// Translate ncurses input to an ABC80 key code.
// Returns 0 if no key is available or the input is not recognised.
static bool esc_pending = false;  // true when 0x1B was seen last call

static uint8_t read_key(void) {
    int ch = getch();

    // Resolve a cached ESC.
    // The previous call saw 0x1B and deferred action.
    // Now we know what (if anything) followed it.
    if (esc_pending) {
        esc_pending = false;
        if (ch == ERR) {
            // Nothing followed the ESC -> bare ESC key -> quit.
            done = true;
            return 0;
        }
        // ESC + char = Option/Alt modifier combo.  Map to ABC80 codes.
        switch (ch) {
            case '4':           return 0x24;  // Option+4  -> ¤
            case 'e': case 'E': return 0x60;  // Option+e  -> é
            case 'u': case 'U': return 0x7E;  // Option+u  -> ü
            default:            return 0;     // unknown combo, swallow
        }
    }

    if (ch == ERR)
        return 0;

    switch (ch) {
        // Cache ESC; do NOT exit yet -- it might be an Option-key prefix.
        case 0x1B:
            esc_pending = true;
            return 0;

        case 0x7F:                   // DEL -> backspace
        case 0x08:  return 0x08;
        case 0x0A:                   // LF -> CR (BASIC expects CR)
        case 0x0D:  return 0x0D;

        // UTF-8 2-byte sequences: Nordic letters and special symbols.
        // Both lead bytes (0xC2 and 0xC3) are handled by utf8_to_abc80_char.
        case 0xC2:
        case 0xC3: {
            int b2 = getch();
            return utf8_to_abc80_char((unsigned char)ch, (unsigned char)b2);
        }

        // Silently consume other multi-byte UTF-8 lead bytes (e.g. 0xE2 for €)
        // so stray continuation bytes do not pollute later reads.
        case 0xE2: case 0xE3: case 0xE4: case 0xE5: case 0xE6: case 0xE7:
        case 0xE8: case 0xE9: case 0xEA: case 0xEB: case 0xEC: case 0xED:
        case 0xEE: case 0xEF:
            getch(); getch();   // discard two continuation bytes
            return 0;
        case 0xF0: case 0xF1: case 0xF2: case 0xF3:
            getch(); getch(); getch();  // discard three continuation bytes
            return 0;

        // Arrow key support (as far as remembered from the ABC80 editing model)
        case KEY_LEFT:  return 0x08;  // cursor left (erasing)
        case KEY_RIGHT: return 0x09;  // cursor right (reveals characters)

        default:
            if (ch >= 0x20 && ch <= 0x7E)
                return (uint8_t) ch;
            return 0;
    }
}



// SCREEN RAM HELPERS

// ELOAD / ESAVE / ELIB -- host file I/O for BASIC programs
// -----------------------------------------------------------
// The ABC80 line input buffer IS the screen RAM. The current input row
// is m[0xFDF3] (index into rowstart[]). On CR we read that row, check
// for our commands, and handle them in C before BASIC sees the line.
//
// BASIC program memory layout (from ROM analysis):
//   m[0xFE1C..1D] = program start address (set by RAM test at boot)
//   m[0xFE1E..1F] = end of program / start of variable area
//   m[0xFE20..21] = end of variable area / start of free space
//
// We save/load the raw tokenised bytes [start, end) as a flat .BAC file.

// Read the current input row from screen RAM into buf.
// Strips bit 7 (ABC80 attribute), removes trailing spaces, null-terminates.
static void read_screen_line(char *buf, int buflen) {
    uint8_t row = m[0xFDF3];
    if (row >= 24) { buf[0] = 0; return; }

    uint16_t base = rowstart[row];
    int len = 0;
    for (int col = 0; col < 40 && len < buflen - 1; col++) {
        uint8_t c = m[base + col] & 0x7F;
        buf[len++] = (c < 0x20) ? ' ' : (char) c;
    }
    buf[len] = 0;
    while (len > 0 && buf[len - 1] == ' ')
        buf[--len] = 0;
}

// Display a status message in response to one of our intercepted commands.
//
// The ABC80 line input routine maintains 2 parallel buffers:
//  - Screen RAM  (non-linear, via rowstart[]) - what is visible (BUF1)
//  - $FE40-$FEB7 (flat, 120-byte)             - what BASIC tokenises on CR (BUF2)
//
//   1. Write the message into screen RAM at the CURRENT cursor row,
//      overwriting the command the user typed. Immediately visible.
//   2. Put $0D into $FE40[0] so BASIC sees an empty (CR-only) line.
//   3. Reset $FDF4 (column counter) to 0.
//   4. Advance $FDF3 (row counter) by 1. BASIC's prompt routine outputs
//      CR+LF before printing prompt, so starting from row+1 puts the
//      prompt on row+2, leaving our message on row undisturbed.
//   5. The caller delivers the CR keystroke as normal. BASIC reads $FE40,
//      sees $0D = empty line, and loops back to the prompt cleanly.
//
// Also updates emul_status so the info bar reflects the last event.
static void screen_msg(const char *msg) {
    uint8_t row = m[0xFDF3];
    if (row >= 24) row = 23;

    uint16_t base = rowstart[row];
    int col;
    for (col = 0; col < 40 && msg[col]; col++)
        m[base + col] = (uint8_t) msg[col];
    for (; col < 40; col++)
        m[base + col] = 0x20;

    m[0xFE40] = 0x0D;
    m[0xFDF4] = 0;
    if (row < 23)
        m[0xFDF3] = row + 1;

    snprintf(emul_status, sizeof(emul_status), "%s", msg);
}

// Extract the filename argument from a command line like "ESAVE foo" or
// 'ELOAD "myfile"'. Writes result into fname[flen], appends .BAC if no
// extension present.  Returns false if no filename was found.
static bool extract_filename(const char *line, int skip, char *fname, int flen) {
    const char *p = line + skip;
    while (*p == ' ') p++;
    if (*p == '"' || *p == 39) p++;   // strip leading quote (39 = ')
    char *out = fname;
    char *end_out = fname + flen - 1;
    while (*p && *p != '"' && *p != 39 && *p != ' ' && out < end_out)
        *out++ = *p++;
    *out = 0;
    if (fname[0] == 0) return false;
    if (!strchr(fname, '.'))
        strncat(fname, ".BAC", (size_t)(flen - (int)strlen(fname) - 1));
    return true;
}

static bool try_file_command(void) {
    char line[48];
    read_screen_line(line, sizeof(line));

    bool is_save  = (strncasecmp(line, "ESAVE", 5) == 0);
    bool is_load  = (strncasecmp(line, "ELOAD", 5) == 0);
    bool is_list  = (strncasecmp(line, "ELIB",  4) == 0);
    bool is_elist = (strncasecmp(line, "ELIST", 5) == 0);
    bool is_etext = (strncasecmp(line, "ETEXT", 5) == 0);

    if (!is_save && !is_load && !is_list && !is_elist && !is_etext)
        return false;

    // Read program memory bounds from BASIC system variables.
    uint16_t prog_start = (uint16_t)(m[0xFE1C] | (m[0xFE1D] << 8));
    uint16_t prog_end   = (uint16_t)(m[0xFE1E] | (m[0xFE1F] << 8));

    if (is_list) {
        // ELIB -- list .BAC files in the current directory.
        // Filenames (without extension) are written space-separated across
        // one screen row.
        char listbuf[41] = {0};
        int pos = 0;
        DIR *dir = opendir(".");
        if (dir) {
            struct dirent *ent;
            while ((ent = readdir(dir)) != NULL && pos < 38) {
                char *dot = strrchr(ent->d_name, '.');
                if (dot && strcasecmp(dot, ".BAC") == 0) {
                    int nlen = (int)(dot - ent->d_name);
                    if (pos + nlen + 1 < 40) {
                        if (pos > 0) listbuf[pos++] = ' ';
                        memcpy(listbuf + pos, ent->d_name, (size_t) nlen);
                        pos += nlen;
                    }
                }
            }
            closedir(dir);
        }
        screen_msg(pos > 0 ? listbuf : "NO FILES");
        snprintf(emul_status, sizeof(emul_status),
                 "DIR: %s", pos > 0 ? listbuf : "(empty)");
        return true;
    }

    if (is_elist) {
        // ELIST <filename> -- capture the output of BASIC's LIST command to a
        // plain-text .BAS file.  We open the file here, then rewrite the input
        // buffer so BASIC sees 'LIST"E"' and runs it in device (non-pause) mode.
        // The run() loop intercepts each output line via a PC hook at 0x0B74.
        char fname[40];
        if (!extract_filename(line, 5, fname, sizeof(fname))) {
            screen_msg("FILENAME MISSING");
            return true;
        }
        // extract_filename adds .BAC by default; we want .BAS instead.
        char *dot = strrchr(fname, '.');
        if (dot && strcasecmp(dot, ".BAC") == 0)
            strcpy(dot, ".BAS");

        if (list_out) fclose(list_out);
        list_out = fopen(fname, "w");
        if (!list_out) { screen_msg("CANNOT CREATE FILE"); return true; }

        // Rewrite $FE40 so BASIC sees LIST"E" (device mode).
        // The quoted argument triggers the non-interactive device path in the
        // ROM: every line is output without pausing to wait for keypresses.
        m[0xFE40]='L'; m[0xFE41]='I'; m[0xFE42]='S'; m[0xFE43]='T';
        m[0xFE44]='"'; m[0xFE45]='E'; m[0xFE46]='"'; m[0xFE47]=0x0D;

        snprintf(emul_status, sizeof(emul_status), "LISTING -> %s", fname);
        return true;
    }

    if (is_etext) {
        // ETEXT <filename> -- load a plain-text BASIC listing back into the
        // interpreter line by line.  We open the file here; etext_inject_step()
        // injects each line into the keyboard buffer and delivers CR so BASIC
        // tokenises and stores it exactly as if the user had typed it.
        char fname[40];
        if (!extract_filename(line, 5, fname, sizeof(fname))) {
            screen_msg("FILENAME MISSING");
            return true;
        }
        char *dot = strrchr(fname, '.');
        if (dot && strcasecmp(dot, ".BAC") == 0) strcpy(dot, ".BAS");

        if (etext_file) { fclose(etext_file); etext_file = NULL; }
        etext_file = fopen(fname, "r");
        if (!etext_file) { screen_msg("FILE NOT FOUND"); return true; }
        etext_delay = ETEXT_LINE_DELAY;
        screen_msg("LOADING..");
        snprintf(emul_status, sizeof(emul_status), "TEXT LOAD -> %s", fname);
        return true;
    }

    char fname[40];
    if (!extract_filename(line, 5, fname, sizeof(fname))) {
        screen_msg("FILENAME MISSING");
        return true;
    }

    if (is_save) {
        if (prog_end <= prog_start) {
            screen_msg("NOTHING TO SAVE");
            return true;
        }
        FILE *f = fopen(fname, "wb");
        if (!f) { screen_msg("CANNOT CREATE FILE"); return true; }
        fwrite(m + prog_start, 1, prog_end - prog_start, f);
        fclose(f);
        char msg[48];
        unsigned nbytes = (unsigned)(prog_end - prog_start);
        snprintf(msg, sizeof(msg), "SAVED %u BYTES", nbytes);
        screen_msg(msg);
        snprintf(emul_status, sizeof(emul_status),
                 "SAVED %u B  @%04X-%04X  -> %s",
                 nbytes, prog_start, prog_end, fname);

    } else {
        FILE *f = fopen(fname, "rb");
        if (!f) { screen_msg("FILE NOT FOUND"); return true; }
        size_t n = fread(m + prog_start, 1, 0x7BFF - prog_start, f);
        fclose(f);

        uint16_t new_end = prog_start + (uint16_t) n;

        // Write the end-of-program marker.  LIST scans for $01 at the start
        // of each line entry to know when the program ends.  Without this byte
        // LIST walks off into garbage RAM and hangs.
        m[new_end] = 0x01;

        // Update the program-end pointer.
        m[0xFE1E] = new_end & 0xFF;
        m[0xFE1F] = new_end >> 8;

        // Reset the variable area to empty, one past prog_end, matching what
        // BASIC's own NEW / clear command does.
        uint16_t var_start = new_end + 1;
        m[0xFE20] = var_start & 0xFF;
        m[0xFE21] = var_start >> 8;

        // Clear remaining interpreter state that NEW resets, so that RUN works
        // cleanly after ELOAD without stale FOR/GOSUB context.
        m[0xFE0C] = 0x82;
        m[0xFE25] = 0x00;
        m[0xFE29] = 0x00;
        m[0xFE2A] = 0x00;
        m[0xFE33] = 0x00;
        m[0xFE35] = 0x00;
        m[0xFE38] = 0x00;

        char msg[48];
        snprintf(msg, sizeof(msg), "LOADED %u BYTES", (unsigned) n);
        screen_msg(msg);
        snprintf(emul_status, sizeof(emul_status),
                 "LOADED %u B  @%04X-%04X  <- %s",
                 (unsigned) n, prog_start, new_end, fname);
    }

    return true;
}

static void keyboard_poll(void) {
    if (pending_key != 0)
        return;

    uint8_t ch = read_key();
    if (ch == 0)
        return;

    // On CR, check for one of our file commands.  screen_msg() will have
    // already rewritten $FE40 to a bare $0D (empty line) and advanced $FDF3
    // by one row, so BASIC will see a blank CR and loop back to its prompt
    // cleanly -- without executing the original command text.
    if (ch == 0x0D)
        try_file_command();

    pending_key = ch | 0x80;
    key_reads   = 2;

    // Pre-write the ISR latch so the fast path (BIT 7,(ix+2)) in the BASIC
    // input loop fires immediately after the next interrupt.
    m[0xFDF5] = pending_key;
}

u8 port_in(u8 port) {
    // KB_PORT (0x38) = INP(56): return the pending keycode, consuming it.
    if (port == KB_PORT) {
        if (key_reads <= 0)
            return 0;
        uint8_t val = pending_key;
        if (--key_reads == 0) {
            pending_key = 0;
            m[0xFDF5]   = 0;
        }
        return val;
    }

    // B_PORT (0x3A) = INP(58): PIO port B.
    // All lines idle-high = no B device connected.
    // Returning 0 would hold every line low, locking up the bus handshake.
    if (port == B_PORT)
        return 0xFF;

    return 0;
}

void port_out(u8 port, u8 val) {
    if (port != 6) return;
    // Port 6 drives the speaker / buzzer:
    //   $00 = silence/reset  (first half of BEL sequence, ignore)
    //   $83 = BEL tone       (second half: ROM does OUT 6,$00 then OUT 6,$83)
    //   $80 = break/STOP sound (keyboard ISR when Ctrl-C/break is detected)
    if (val == 0x83 || val == 0x80)
        write(STDOUT_FILENO, "\a", 1);
}



// DISPLAY

static void screen_refresh(void) {
    for (int row = 0; row < 24; row++) {
        for (int col = 0; col < 40; col++) {
            uint8_t cell = m[rowstart[row] + col];

            if (cell & 0x80) {
                attron(A_BLINK);
                mvaddch(row, col, '_');
                attroff(A_BLINK);
                continue;
            }

            const char *utf8 = abc80_to_utf8(cell);
            if (utf8) {
                mvprintw(row, col, "%s", utf8);
            } else {
                mvaddch(row, col, cell & 0x7F);
            }
        }
    }
    refresh();
}

// Render emulator state in rows below the 24-row ABC80 screen.
// Only draws rows that fit in the current terminal.
//
//   Row 24: Z80 registers (PC, SP, A, BC, DE, HL, IX, IY)
//   Row 25: Flags (S Z H P N C), interrupt mode/state, step counter
//   Row 26: Last emulator event / file-operation status
static void status_refresh(void) {
    int maxrow = getmaxy(stdscr);

    if (maxrow > 24) {
        mvprintw(24, 0,
            "PC:%04X SP:%04X  A:%02X  BC:%02X%02X  DE:%02X%02X  "
            "HL:%02X%02X  IX:%04X  IY:%04X",
            pc, sp, a, b, c, d, e, h, l, ix, iy);
        clrtoeol();
    }

    if (maxrow > 25) {
        mvprintw(25, 0,
            "SF:%d ZF:%d HF:%d PF:%d NF:%d CF:%d  "
            "IM:%d IFF:%d/%d  HALT:%d  Steps:%-12lld",
            (int)sf, (int)zf, (int)hf, (int)pf, (int)nf, (int)cf,
            im, (int)iff1, (int)iff2, (int)halted, total_steps);
        clrtoeol();
    }

    if (maxrow > 26) {
        mvprintw(26, 0, "[ %-60s ]", emul_status);
        clrtoeol();
    }
}



// ELIST CAPTURE  (PC hooks, called before each step())

// Check whether the Z80 PC is at one of the two ROM hooks used to capture
// LIST output and, if so, intercept and redirect execution.
//
//   PC=0x0B74: ROM is about to CALL 0x0896 (write line to B device).
//     BC = byte count of the detokenised line in m[0xFE40..0xFE40+BC-1].
//     We capture the text here and skip the CALL by advancing PC to 0x0B77
//     (the JR that follows), so no actual B bus I/O happens.
//
//   PC=0x0B9D: ROM is about to CALL NZ,0x087F (close B device).
//     This is reached only after the last program line has been listed.
//     We close our file and skip the CALL so no B bus I/O is attempted.
static void elist_capture_step(void) {
    if (!list_out) return;

    if (pc == 0x0B74) {
        uint16_t count = ((uint16_t)b << 8) | c;
        for (uint16_t i = 0; i < count; i++) {
            uint8_t ch = m[0xFE40 + i];
            const char *utf8 = abc80_to_utf8(ch);
            if (utf8)            fputs(utf8, list_out);
            else if (ch == 0x0A) fputc('\n', list_out);
            else if (ch >= 0x20) fputc((char)ch, list_out);
        }
        pc = 0x0B77;  // skip CALL 0x0896; step() will execute the JR
    }

    if (pc == 0x0B9D) {
        fclose(list_out);
        list_out = NULL;
        screen_msg("LISTING SAVED");
        pc = 0x0BA0;  // skip CALL NZ,0x087F; step() runs frame teardown
    }
}



// ETEXT INJECTION  (called once per step)

// Feed one character of the open ETEXT file into the keyboard buffer.
//
// Lines are read from the .BAS file, translated from UTF-8 to ABC80 codes,
// and injected one character at a time exactly as keyboard input.  After
// each CR a delay (ETEXT_LINE_DELAY steps) is inserted to give BASIC time
// to tokenise and store the line before the next one arrives.
static void etext_inject_step(void) {
    if (etext_delay > 0) { etext_delay--; return; }
    if (!etext_file || pending_key != 0) return;

    if (etext_pos < etext_len) {
        // Deliver the next character of the buffered line.
        uint8_t ch  = etext_buf[etext_pos++];
        pending_key = ch | 0x80;
        key_reads   = 2;
        m[0xFDF5]   = pending_key;
        // After CR: give BASIC time to tokenise+store before the next line.
        if (ch == 0x0D)
            etext_delay = ETEXT_LINE_DELAY;
        return;
    }

    // Current line exhausted — load the next line from the file.
    // Skip blank lines (after stripping CR/LF) to avoid sending empty
    // BASIC lines that would add line-number-less entries to the program.
    char rawbuf[128];
    int rlen = 0;
    while (!rlen && fgets(rawbuf, sizeof(rawbuf), etext_file)) {
        rlen = (int)strlen(rawbuf);
        while (rlen > 0 && (rawbuf[rlen-1] == '\n' || rawbuf[rlen-1] == '\r'))
            rawbuf[--rlen] = 0;
    }

    if (rlen > 0) {
        // Translate UTF-8 text to ABC80 SIS-662241 character codes.
        int out = 0;
        for (int i = 0; rawbuf[i] && out < 118; ) {
            unsigned char c  = (unsigned char)rawbuf[i];
            unsigned char c2 = (unsigned char)rawbuf[i+1];
            if ((c == 0xC2 || c == 0xC3) && c2) {
                uint8_t abc = utf8_to_abc80_char(c, c2);
                if (abc) { etext_buf[out++] = abc; i += 2; }
                else      { i++; }  // skip lead byte; c2 processed next iter
                continue;
            }
            if (c >= 0x20) etext_buf[out++] = c;
            i++;
        }
        etext_buf[out++] = 0x0D;
        etext_len = out;
        etext_pos = 0;
    } else {
        // File exhausted — close and signal BASIC.
        fclose(etext_file);
        etext_file = NULL;
        screen_msg("TEXT LOADED");
        // Deliver a bare CR so BASIC processes the empty line
        // (m[0xFE40]=0x0D was set by screen_msg) and loops to prompt.
        pending_key = 0x0D | 0x80;
        key_reads   = 2;
        m[0xFDF5]   = pending_key;
        screen_msg("ABC80");  // fake prompt on next row
    }
}



// SIGNAL HANDLER

// Ctrl-C: set the ABC80 break flag instead of killing the process.
// The BASIC interpreter checks m[0xFE07] between every statement and
// jumps to its break handler when it is non-zero.
static void ctrlc_handler(int sig) {
    (void) sig;
    m[0xFE07] = 0x83;
}



// EMULATION LOOP

static void run(void) {
    setlocale(LC_ALL, "");

    // Catch SIGINT (Ctrl-C) and convert it to an ABC80 BREAK.
    // We use a signal handler rather than raw input because cbreak()
    // leaves terminal ISIG enabled (needed so Ctrl-Z / SIGTSTP works).
    signal(SIGINT, ctrlc_handler);

    init();
    memcpy(m, abcprom, sizeof(abcprom));

    initscr();
    cbreak();
    noecho();
    nodelay(stdscr, true);
    nonl();
    keypad(stdscr, true);   // decode arrow keys into KEY_LEFT / KEY_RIGHT

    pc = 0x0000;

    snprintf(emul_status, sizeof(emul_status),
             "ABC80 EMU  ROM: %uKB  RAM: 16KB  CPU: Z80 @3MHz",
             (unsigned)(sizeof(abcprom) / 1024));

    long long    strobe_ns   = 1000000000LL / STROBE_HZ;
    long long    next_strobe = now_ns() + strobe_ns;
    unsigned int steps       = 0;

    while (!done) {
        // 1. Check ELIST PC hooks before the instruction executes.
        elist_capture_step();

        // 2. Execute one Z80 instruction (or NOP if halted).
        step();
        steps++;
        total_steps++;

        // 3. Advance ETEXT injection (one char per step, with delay after CR).
        etext_inject_step();

        // 4. Poll the keyboard; inject into emulator if a key is ready.
        keyboard_poll();

        // 5. Keyboard strobe: generate interrupt at 50 Hz.
        if (steps >= STEPS_PER_STROBE) {
            steps = 0;
            long long now = now_ns();
            if (now >= next_strobe) {
                next_strobe = now + strobe_ns;
                gen_int(KB_INT_VEC);
            }
        }

        // 6. Refresh the ncurses display (screen + status bar).
        if (steps % STEPS_PER_REFRESH == 0) {
            screen_refresh();
            status_refresh();
        }
    }

    screen_refresh();
    status_refresh();
    endwin();
    putchar('\n');
}

int main(void) {
    run();
}
