// AIRFIGHT for ABC80 -- Z80 assembly
// Original BASIC: Kristian Lidberg & Set Lonnert, 1981
// Load with monitor command P, then: AS 8000  G 8000
// Phase 1+2+3+4: constants, RAM layout, screen primitives, sound, delay, input
#pragma once

static const char airfight_src[] =
// --- Hardware ---
"PORT_SND    EQU 006H\n"
"PORT_KB     EQU 038H\n"
"CLKLO       EQU 0FDF0H\n"
// --- Sound values ---
"SOUND_OFF   EQU 0\n"
"SOUND_INTRO EQU 135\n"
"SOUND_TITLE EQU 157\n"
"SOUND_READY EQU 131\n"
"SOUND_SH1   EQU 155\n"
"SOUND_SH2   EQU 157\n"
"SOUND_HIT   EQU 9\n"
"SOUND_WIN   EQU 199\n"
"SOUND_LOOP  EQU 137\n"
"SOUND_TUNE  EQU 121\n"
// --- Screen byte constants ---
"SCR_BLANK   EQU 020H\n" // 32
"SCR_BLOCK   EQU 07FH\n" // 127
"SCR_GFXMK   EQU 097H\n" // 151
"CHAR_GFX    EQU 017H\n" // 23
// --- Player key codes ---
"P1_LEFT     EQU 041H\n"
"P1_RIGHT    EQU 044H\n"
"P1_FIRE     EQU 020H\n"
"P2_LEFT     EQU 04AH\n"
"P2_RIGHT    EQU 04CH\n"
"P2_FIRE     EQU 04DH\n"
// --- Game constants ---
"SCORE_LIM   EQU 10\n"
"TIME_MIN    EQU 2\n"
"DIR_CNT     EQU 8\n"
"BUL_STEPS   EQU 3\n"
// --- Variable block at 8F00H ---
"VAR_BASE    EQU 08F00H\n"
"CUR_ROW     EQU VAR_BASE+0\n"
"CUR_COL     EQU VAR_BASE+1\n"
"P_DIR       EQU VAR_BASE+2\n"
"P_ROW       EQU VAR_BASE+6\n"
"P_COL       EQU VAR_BASE+10\n"
"P_PROW      EQU VAR_BASE+14\n"
"P_PCOL      EQU VAR_BASE+18\n"
"P_SCORE     EQU VAR_BASE+22\n"
"B_ACTIVE    EQU VAR_BASE+26\n"
"B_DIR       EQU VAR_BASE+28\n"
"B_ROW       EQU VAR_BASE+32\n"
"B_COL       EQU VAR_BASE+36\n"
"B_PROW      EQU VAR_BASE+40\n"
"B_PCOL      EQU VAR_BASE+44\n"
"J_PREV      EQU VAR_BASE+48\n"
"MODE_SLIM   EQU VAR_BASE+50\n"
"MODE_STGT   EQU VAR_BASE+52\n"
"MODE_TDIR   EQU VAR_BASE+54\n"
"TMIN_V      EQU VAR_BASE+56\n"
"TSEC_V      EQU VAR_BASE+58\n"
"WINNER_V    EQU VAR_BASE+60\n"
"PLAYED_V    EQU VAR_BASE+62\n"
"NAME_P1     EQU VAR_BASE+64\n"
"NAME_P2     EQU VAR_BASE+96\n"
"INBUF       EQU VAR_BASE+128\n"   // 16-byte scratch buffer for Phase 4 test
// ---------------------------------------------------------------------------
"        ORG 8000H\n"
// ---------------------------------------------------------------------------
// Phase 5 test:
//   Block-graphic logo on rows 2-4 (DRAWBDR makes rows graphic;
//   lowercase = mosaic pattern, uppercase = regular font in graphic rows).
//   Print all game strings rows 6-19 to verify display.
//   Wait for Ctrl-C.
"START:\n"
"        DI\n"
"        CALL CLRSCR\n"
// --- Logo: rows 2-4 in graphics mode ---
"        LD B, 2\n"
"        LD C, 4\n"
"        CALL DRAWBDR\n"
"        LD B, 2\n"
"        LD C, 1\n"
"        CALL CSRSET\n"
"        LD HL, LOGO_BAR\n"
"        CALL PRTSTR\n"
"        LD B, 3\n"
"        LD C, 16\n"
"        CALL CSRSET\n"
"        LD HL, LOGO_TITLE\n"
"        CALL PRTSTR\n"
"        LD B, 4\n"
"        LD C, 1\n"
"        CALL CSRSET\n"
"        LD HL, LOGO_BAR\n"
"        CALL PRTSTR\n"
// --- Game strings rows 6-19 ---
"        LD B, 6\n"
"        LD C, 0\n"
"        CALL CSRSET\n"
"        LD HL, TXT_PLAYED\n"
"        CALL PRTSTR\n"
"        LD B, 7\n"
"        LD C, 0\n"
"        CALL CSRSET\n"
"        LD HL, TXT_NAME_P1\n"
"        CALL PRTSTR\n"
"        LD B, 8\n"
"        LD C, 0\n"
"        CALL CSRSET\n"
"        LD HL, TXT_NAME_P2\n"
"        CALL PRTSTR\n"
"        LD B, 9\n"
"        LD C, 0\n"
"        CALL CSRSET\n"
"        LD HL, TXT_MODE_Q\n"
"        CALL PRTSTR\n"
"        LD B, 10\n"
"        LD C, 0\n"
"        CALL CSRSET\n"
"        LD HL, TXT_MODE_SCORE\n"
"        CALL PRTSTR\n"
"        LD B, 11\n"
"        LD C, 0\n"
"        CALL CSRSET\n"
"        LD HL, TXT_MODE_TIME\n"
"        CALL PRTSTR\n"
"        LD B, 12\n"
"        LD C, 0\n"
"        CALL CSRSET\n"
"        LD HL, TXT_READY\n"
"        CALL PRTSTR\n"
"        LD B, 13\n"
"        LD C, 0\n"
"        CALL CSRSET\n"
"        LD HL, TXT_FIRE\n"
"        CALL PRTSTR\n"
"        LD B, 14\n"
"        LD C, 0\n"
"        CALL CSRSET\n"
"        LD HL, TXT_WIN_P1\n"
"        CALL PRTSTR\n"
"        LD B, 15\n"
"        LD C, 0\n"
"        CALL CSRSET\n"
"        LD HL, TXT_WIN_P2\n"
"        CALL PRTSTR\n"
"        LD B, 16\n"
"        LD C, 0\n"
"        CALL CSRSET\n"
"        LD HL, TXT_AGAIN\n"
"        CALL PRTSTR\n"
"        LD B, 17\n"
"        LD C, 0\n"
"        CALL CSRSET\n"
"        LD HL, TXT_SCORE_P1\n"
"        CALL PRTSTR\n"
"        LD B, 18\n"
"        LD C, 0\n"
"        CALL CSRSET\n"
"        LD HL, TXT_SCORE_P2\n"
"        CALL PRTSTR\n"
"        LD B, 19\n"
"        LD C, 0\n"
"        CALL CSRSET\n"
"        LD HL, TXT_TIME\n"
"        CALL PRTSTR\n"
// --- Wait for Ctrl-C ---
"        LD B, 22\n"
"        LD C, 0\n"
"        CALL CSRSET\n"
"        LD HL, TXT_WAIT\n"
"        CALL PRTSTR\n"
"WAIT:\n"
"        IN A, (PORT_KB)\n"
"        AND 07FH\n"
"        CP 003H\n"
"        JR NZ, WAIT\n"
"        EI\n"
"        RET\n"
// ---------------------------------------------------------------------------
// Phase 2 — Screen primitives
// ---------------------------------------------------------------------------
// CSRSET -- set cursor  (B=row, C=col)
"CSRSET:\n"
"        LD A, B\n"
"        LD (CUR_ROW), A\n"
"        LD A, C\n"
"        LD (CUR_COL), A\n"
"        RET\n"
// PRTCHR -- write char A at cursor, advance CUR_COL
"PRTCHR:\n"
"        PUSH AF\n"
"        LD A, (CUR_ROW)\n"
"        LD B, A\n"
"        LD A, (CUR_COL)\n"
"        LD C, A\n"
"        POP AF\n"
"        CALL PUTCHR\n"
"        LD A, (CUR_COL)\n"
"        INC A\n"
"        LD (CUR_COL), A\n"
"        RET\n"
// PRTSTR -- print null-terminated string (HL=ptr)
// PUSH/POP HL because SCRADDR (inside PUTCHR) clobbers HL.
"PRTSTR:\n"
"        LD A, (HL)\n"
"        OR A\n"
"        RET Z\n"
"        PUSH HL\n"
"        CALL PRTCHR\n"
"        POP HL\n"
"        INC HL\n"
"        JR PRTSTR\n"
// CLRSCR -- clear all 24 rows: col 0 = 00H, cols 1-39 = space
"CLRSCR:\n"
"        LD B, 24\n"
"        LD HL, ROWTAB\n"
"CLRLP:\n"
"        LD E, (HL)\n"
"        INC HL\n"
"        LD D, (HL)\n"
"        INC HL\n"
"        PUSH BC\n"
"        PUSH HL\n"
"        EX DE, HL\n"
"        LD (HL), 000H\n"
"        INC HL\n"
"        LD B, 39\n"
"CLRL2:\n"
"        LD (HL), SCR_BLANK\n"
"        INC HL\n"
"        DJNZ CLRL2\n"
"        POP HL\n"
"        POP BC\n"
"        DJNZ CLRLP\n"
"        RET\n"
// DRAWBDR -- write CHAR_GFX (017H) to col 0 of rows B..C inclusive
// This switches those rows to graphics mode
// Typically as in the original: FOR G%=B TO C : CUR(G%,0) : CHR$(23) : NEXT G%
"DRAWBDR:\n"
"        PUSH BC\n"
"        LD D, B\n"
"        LD E, C\n"
"DBRLP:\n"
"        LD B, D\n"
"        LD C, 0\n"
"        LD A, CHAR_GFX\n"
"        CALL PUTCHR\n"
"        LD A, D\n"
"        CP E\n"
"        JR Z, DBREND\n"
"        INC D\n"
"        JR DBRLP\n"
"DBREND:\n"
"        POP BC\n"
"        RET\n"
// Phase 3 — Sound + delay
"SNDON:\n"
"        PUSH AF\n"
"        XOR A\n"
"        OUT (PORT_SND), A\n"
"        POP AF\n"
"        OUT (PORT_SND), A\n"
"        RET\n"
"SNDOFF:\n"
"        XOR A\n"
"        OUT (PORT_SND), A\n"
"        RET\n"
// DLYLOOP -- wait HL 50Hz ticks  (clobbers A, B, DE; HL=0 on return)
"DLYLOOP:\n"
"        LD DE, CLKLO\n"
"        LD A, (DE)\n"
"DLYO:\n"
"        LD B, A\n"
"DLYI:\n"
"        LD A, (DE)\n"
"        CP B\n"
"        JR Z, DLYI\n"
"        DEC HL\n"
"        LD A, H\n"
"        OR L\n"
"        RET Z\n"
"        JR DLYO\n"
// Low-level screen
"PUTCHR:\n"
"        PUSH AF\n"
"        CALL SCRADDR\n"
"        POP AF\n"
"        LD (HL), A\n"
"        RET\n"
"GETCHR:\n"
"        CALL SCRADDR\n"
"        LD A, (HL)\n"
"        RET\n"
// SCRADDR -- (B=row, C=col) -> HL.  Clobbers A, D, E.  Preserves B, C.
"SCRADDR:\n"
"        LD HL, ROWTAB\n"
"        LD A, B\n"
"        ADD A, A\n"
"        LD D, 0\n"
"        LD E, A\n"
"        ADD HL, DE\n"
"        LD A, (HL)\n"
"        INC HL\n"
"        LD H, (HL)\n"
"        LD L, A\n"
"        LD D, 0\n"
"        LD E, C\n"
"        ADD HL, DE\n"
"        RET\n"
// ---------------------------------------------------------------------------
// Phase 4 — Input routines
// ---------------------------------------------------------------------------
// GETCHR name already taken (screen read); keyboard routine is INKEY
// INKEY -- wait for a keypress, return ASCII in A (bit 7 stripped).
// Drains the second key_reads slot so the key does not auto-repeat.
"INKEY:\n"
"        IN A, (PORT_KB)\n"
"        AND 07FH\n"
"        JR Z, INKEY\n"
"        PUSH AF\n"
"        IN A, (PORT_KB)\n"    // consume second read slot
"        POP AF\n"
"        RET\n"
// INLINE_V -- read a line into buffer at HL, max B chars.
// Echoes chars at current cursor.  Handles backspace (08H).
// Null-terminates on CR.  Clobbers A, B, C, D, HL.
"INLINE_V:\n"
"        LD C, 0\n"            // C=count; B=max passed by caller
"INLP:\n"
"        CALL INKEY\n"
"        CP 00DH\n"
"        JR Z, INLDONE\n"
"        CP 008H\n"
"        JR Z, INLBS\n"
"        LD D, A\n"            // save char; check room first
"        LD A, C\n"
"        CP B\n"
"        JR NC, INLP\n"        // buffer full -- ignore char
"        LD A, D\n"
"        LD (HL), A\n"
"        PUSH BC\n"            // preserve max (B) and count (C)
"        PUSH HL\n"
"        CALL PRTCHR\n"        // echo; clobbers B, C
"        POP HL\n"
"        POP BC\n"
"        INC HL\n"
"        INC C\n"
"        JR INLP\n"
"INLBS:\n"
"        LD A, C\n"
"        OR A\n"
"        JR Z, INLP\n"
"        DEC HL\n"
"        DEC C\n"
"        LD A, (CUR_COL)\n"
"        DEC A\n"
"        LD (CUR_COL), A\n"    // back one column
"        LD A, 020H\n"         // space to erase
"        PUSH BC\n"            // preserve max (B) and count (C)
"        PUSH HL\n"
"        CALL PRTCHR\n"        // overwrite with space; clobbers B, C
"        POP HL\n"
"        POP BC\n"
"        LD A, (CUR_COL)\n"
"        DEC A\n"
"        LD (CUR_COL), A\n"    // back one column again
"        JR INLP\n"
"INLDONE:\n"
"        LD (HL), 0\n"
"        RET\n"
// STRLFT1 -- null-terminate buffer at offset 1 (keep only first char).
// Entry/exit: HL = buffer base (unchanged).
"STRLFT1:\n"
"        INC HL\n"
"        LD (HL), 0\n"
"        DEC HL\n"
"        RET\n"
// ---------------------------------------------------------------------------
// Phase 5 — Game strings  ([=Ä  \=Ö  ]=Å in ABC80 character set)
// ---------------------------------------------------------------------------
// Intro / played-before prompt
"TXT_PLAYED:\n"
"        DEFB \"HAR NI SPELAT F\\RUT? (J/N)\", 0\n"
// Name entry
"TXT_NAME_P1:\n"
"        DEFB \"SPELARE 1 - ANGE NAMN: \", 0\n"
"TXT_NAME_P2:\n"
"        DEFB \"SPELARE 2 - ANGE NAMN: \", 0\n"
// Mode selection  ([=Ä in strings below)
"TXT_MODE_Q:\n"
"        DEFB \"V[LJ SPELL[GE (P=PO[NG T=TID): \", 0\n"
"TXT_MODE_SCORE:\n"
"        DEFB \"PO[NGL[GE: VINNER VID 10\", 0\n"
"TXT_MODE_TIME:\n"
"        DEFB \"TIDSL[GE: 2 MINUTER\", 0\n"
// In-game prompts
"TXT_READY:\n"
"        DEFB \"REDO! TRYCK VALFRI TANGENT\", 0\n"
"TXT_FIRE:\n"
"        DEFB \"SKJUT!\", 0\n"
// End game
"TXT_WIN_P1:\n"
"        DEFB \"SPELARE 1 VINNER!\", 0\n"
"TXT_WIN_P2:\n"
"        DEFB \"SPELARE 2 VINNER!\", 0\n"
"TXT_AGAIN:\n"
"        DEFB \"SPELA IGEN? (J/N)\", 0\n"
// HUD labels
"TXT_SCORE_P1:\n"
"        DEFB \"P1:\", 0\n"
"TXT_SCORE_P2:\n"
"        DEFB \"P2:\", 0\n"
"TXT_TIME:\n"
"        DEFB \"TID:\", 0\n"
// Single-char Y/N choices (for comparison in game logic)
"TXT_YES:\n"
"        DEFB \"J\", 0\n"
"TXT_NO:\n"
"        DEFB \"N\", 0\n"
// Logo: mosaic bar (lowercase '~' in graphics mode = pattern 0x3E, 5/6 pixels lit)
// and title (uppercase in graphics mode = regular font)
"LOGO_BAR:\n"
"        DEFB \"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\"\n"
"        DEFB \"~~~~~~~\", 0\n"
"LOGO_TITLE:\n"
"        DEFB \"AIRFIGHT\", 0\n"
// Ctrl-C exit message (test harness)
"TXT_WAIT:\n"
"        DEFB \"CTRL-C TO EXIT\", 0\n"
// ---------------------------------------------------------------------------
// ROWTAB -- screen-RAM start address for each of the 24 rows (little-endian)
"ROWTAB:\n"
"        DW 07C00H\n"
"        DW 07C80H\n"
"        DW 07D00H\n"
"        DW 07D80H\n"
"        DW 07E00H\n"
"        DW 07E80H\n"
"        DW 07F00H\n"
"        DW 07F80H\n"
"        DW 07C28H\n"
"        DW 07CA8H\n"
"        DW 07D28H\n"
"        DW 07DA8H\n"
"        DW 07E28H\n"
"        DW 07EA8H\n"
"        DW 07F28H\n"
"        DW 07FA8H\n"
"        DW 07C50H\n"
"        DW 07CD0H\n"
"        DW 07D50H\n"
"        DW 07DD0H\n"
"        DW 07E50H\n"
"        DW 07ED0H\n"
"        DW 07F50H\n"
"        DW 07FD0H\n"
    ;
