// Auto-generated from snake.asm - do not edit by hand
#pragma once

static const char snake_src[] =
    "; =============================================================================\n"
    "; SNAKE for ABC80  —  character-cell graphics version\n"
    "; =============================================================================\n"
    ";\n"
    "; The ABC80 screen is 40 columns x 24 rows of character cells.\n"
    "; In graphics mode (triggered by CHR$(151) = 97h in column 0) each cell\n"
    "; is rendered as a 2x3 dot pattern.  Pattern bits 5:0 light the six dots;\n"
    "; the firmware converts a screen byte to its pattern with:\n"
    ";\n"
    ";   pattern = (byte & 1Fh) | ((byte & 40h) >> 1)\n"
    ";\n"
    "; Relevant byte values:\n"
    ";\n"
    ";   7Fh  ->  pattern 3Fh  (111111)  full block  — snake body, walls\n"
    ";   35h  ->  pattern 15h  (010101)  three dots  — food pellet\n"
    ";   20h  ->  pattern 00h  (000000)  no dots     — empty cell / blank\n"
    ";\n"
    "; NOTE: characters in the range 40h-5Fh (A-Z etc.) are always displayed\n"
    "; as text even inside a graphics-mode row; keep game bytes outside that\n"
    "; range.\n"
    ";\n"
    "; SCREEN LAYOUT  (column 0 always holds the 97h graphics-mode marker)\n"
    ";\n"
    ";   Row  0        wall (full blocks, cols 1-39)\n"
    ";   Rows 1-22     play field, 22 rows tall\n"
    ";   Row  23       wall (full blocks, cols 1-39)\n"
    ";   Col  1        left wall  (full blocks, rows 1-22)\n"
    ";   Col  39       right wall (full blocks, rows 1-22)\n"
    ";   Cols 2-38     play area  (37 columns wide)\n"
    ";\n"
    "; SNAKE MECHANICS\n"
    ";   The snake body is stored as a FIFO ring buffer of (row, col) byte pairs\n"
    ";   in RAM at SBUF (9000h), holding up to 64 body segments.  SHEAD indexes\n"
    ";   the newest cell (the head); STAIL indexes the oldest (the tail).\n"
    ";\n"
    ";   Every move tick:\n"
    ";     1. Fetch head position from SBUF[SHEAD].\n"
    ";     2. Apply direction delta -> new (row, col).\n"
    ";     3. Read the screen byte at the new cell.\n"
    ";        BLOCK (7Fh)  -> wall or self hit -> GAME OVER\n"
    ";        FOOD  (35h)  -> eat pellet: grow (skip tail erase), place new food.\n"
    ";        BLANK (20h)  -> normal move: erase SBUF[STAIL] from screen, slide.\n"
    ";     4. Write new head into SBUF[SHEAD], draw BLOCK there.\n"
    ";\n"
    ";   Because the screen itself acts as a spatial lookup, self-collision is\n"
    ";   detected for free: every body segment is BLOCK, so running into one\n"
    ";   triggers GAME OVER exactly like hitting a wall.\n"
    ";\n"
    "; TIMING\n"
    ";   The main loop syncs to the ABC80 50 Hz hardware clock at FDF0h.\n"
    ";   The snake moves every 4th tick (~12.5 Hz).\n"
    ";\n"
    "; CONTROLS\n"
    ";   W = up     S = down     A = left     D = right   (upper or lower case)\n"
    ";   Ctrl-C = quit back to the monitor\n"
    ";\n"
    "; HOW TO RUN FROM THE MONITOR\n"
    ";   P        load this source into the ASM editor\n"
    ";   AS 8000  assemble at address 8000h\n"
    ";   G 8000   run  (Ctrl-C returns to monitor)\n"
    "; =============================================================================\n"
    "\n"
    "; ---------------------------------------------------------------------------\n"
    "; Z80 RAM  —  game variables at 8F00h (well above the assembled code).\n"
    "; Each variable is one byte.\n"
    "; ---------------------------------------------------------------------------\n"
    "\n"
    "SHEAD   EQU 08F00H  ; ring-buffer head index  (0-63, wraps with AND 3Fh)\n"
    "STAIL   EQU 08F01H  ; ring-buffer tail index  (0-63)\n"
    "DIR     EQU 08F02H  ; current direction: 0=right 1=down 2=left 3=up\n"
    "NDIR    EQU 08F03H  ; next (pending) direction from keyboard\n"
    "PCLK    EQU 08F04H  ; previous 50 Hz clock byte  (for edge detection)\n"
    "SPEED   EQU 08F05H  ; frame counter — move tick every 4th frame\n"
    "RNG     EQU 08F06H  ; Galois LFSR state for pseudo-random food placement\n"
    "KEY     EQU 08F07H  ; ASCII code of key read this frame (bit 7 stripped)\n"
    "PFROW   EQU 08F08H  ; food-placement scratch: candidate row\n"
    "PFCOL   EQU 08F09H  ; food-placement scratch: candidate column\n"
    "\n"
    "; ---------------------------------------------------------------------------\n"
    "; Ring buffer  —  64 entries × 2 bytes = 128 bytes.\n"
    ";   Entry i is at: SBUF + i*2 + 0 = row,  SBUF + i*2 + 1 = col.\n"
    ";   With i in 0..63, i*2 is 0..126, so the high byte of SBUF + i*2 is always\n"
    ";   90h — address = 90h:L where L = i*2.\n"
    "; ---------------------------------------------------------------------------\n"
    "\n"
    "SBUF    EQU 09000H  ; base address of body ring buffer\n"
    "SMASK   EQU 03FH    ; wrap mask for 64 entries  (AND SMASK = mod 64)\n"
    "\n"
    "; ---------------------------------------------------------------------------\n"
    "; Hardware\n"
    "; ---------------------------------------------------------------------------\n"
    "\n"
    "CLKLO   EQU 0FDF0H  ; ABC80 50 Hz real-time clock — low byte\n"
    "\n"
    "; ---------------------------------------------------------------------------\n"
    "; Screen byte constants\n"
    "; ---------------------------------------------------------------------------\n"
    "\n"
    "BLOCK   EQU 07FH    ; full 2×3 block  (pattern 3Fh = all 6 dots lit)\n"
    "BLANK   EQU 020H    ; empty cell      (pattern 00h = no dots)\n"
    "GFXMK   EQU 097H   ; CHR$(151) in col 0 -> switches that row to graphics mode\n"
    "FOOD    EQU 035H    ; food pellet     (pattern 15h = 010101, 3 alternating dots)\n"
    "\n"
    "; ---------------------------------------------------------------------------\n"
    "; Direction constants\n"
    "; ---------------------------------------------------------------------------\n"
    "\n"
    "DRIGHT  EQU 0       ; delta: dcol = +1, drow =  0\n"
    "DDOWN   EQU 1       ; delta: drow = +1, dcol =  0\n"
    "DLEFT   EQU 2       ; delta: dcol = -1 (FFh), drow =  0\n"
    "DUP     EQU 3       ; delta: drow = -1 (FFh), dcol =  0\n"
    "\n"
    "; ---------------------------------------------------------------------------\n"
    "        ORG 8000H\n"
    "; ---------------------------------------------------------------------------\n"
    "\n"
    "; =============================================================================\n"
    "; START — one-time initialisation\n"
    "; =============================================================================\n"
    "START:\n"
    "        DI              ; disable interrupts — we poll the 50 Hz clock ourselves\n"
    "\n"
    "        CALL INITSCR    ; draw border walls, clear play field\n"
    "\n"
    "        ; ---- Seed the RNG by mixing the current clock into whatever is in RNG.\n"
    "        ;     This gives a different starting point each restart based on timing.\n"
    "        ;     The OR A / INC A guard prevents the invalid LFSR state of 0. ----\n"
    "        LD HL, CLKLO\n"
    "        LD A, (HL)      ; A = current 50 Hz clock byte (varies with timing)\n"
    "        XOR (RNG)       ; mix with previous RNG value\n"
    "        OR A\n"
    "        JR NZ, RSEED_OK\n"
    "        INC A           ; RNG must not be 0 (LFSR stops at 0)\n"
    "RSEED_OK:\n"
    "        LD (RNG), A\n"
    "\n"
    "        ; ---- Set up the initial snake  (3 segments, heading right) ----\n"
    "        ;\n"
    "        ;   SBUF[0] = (11, 18)  <-- tail\n"
    "        ;   SBUF[1] = (11, 19)  <-- middle body\n"
    "        ;   SBUF[2] = (11, 20)  <-- head\n"
    "        ;\n"
    "        XOR A\n"
    "        LD (STAIL), A   ; STAIL = 0\n"
    "        LD A, 2\n"
    "        LD (SHEAD), A   ; SHEAD = 2\n"
    "\n"
    "        LD HL, SBUF     ; point to SBUF[0]\n"
    "        LD (HL), 11     ; [0].row = 11\n"
    "        INC HL\n"
    "        LD (HL), 18     ; [0].col = 18\n"
    "        INC HL\n"
    "        LD (HL), 11     ; [1].row = 11\n"
    "        INC HL\n"
    "        LD (HL), 19     ; [1].col = 19\n"
    "        INC HL\n"
    "        LD (HL), 11     ; [2].row = 11\n"
    "        INC HL\n"
    "        LD (HL), 20     ; [2].col = 20\n"
    "\n"
    "        ; ---- Draw initial snake on screen ----\n"
    "        LD B, 11\n"
    "        LD C, 18\n"
    "        LD A, BLOCK\n"
    "        CALL PUTCHR\n"
    "        LD B, 11\n"
    "        LD C, 19\n"
    "        LD A, BLOCK\n"
    "        CALL PUTCHR\n"
    "        LD B, 11\n"
    "        LD C, 20\n"
    "        LD A, BLOCK\n"
    "        CALL PUTCHR\n"
    "\n"
    "        ; ---- Set initial direction = right ----\n"
    "        LD A, DRIGHT\n"
    "        LD (DIR), A\n"
    "        LD (NDIR), A\n"
    "\n"
    "        ; ---- Place the first food pellet ----\n"
    "        CALL PLACEFOOD\n"
    "\n"
    "        ; ---- Snapshot the 50 Hz clock for edge detection ----\n"
    "        LD A, (CLKLO)\n"
    "        LD (PCLK), A\n"
    "\n"
    "        ; ---- Init frame counter ----\n"
    "        XOR A\n"
    "        LD (SPEED), A\n"
    "\n"
    "; =============================================================================\n"
    "; MAIN LOOP — executes once per 50 Hz tick (20 ms)\n"
    "; =============================================================================\n"
    "LOOP:\n"
    "        ; ------------------------------------------------------------------\n"
    "        ; 1.  WAIT FOR THE NEXT 50 Hz TICK\n"
    "        ;     Spin until CLKLO differs from the value saved last iteration.\n"
    "        ; ------------------------------------------------------------------\n"
    "        LD HL, CLKLO\n"
    "WCLK:   LD A, (PCLK)\n"
    "        CP (HL)\n"
    "        JR Z, WCLK      ; same value -> tick not yet arrived\n"
    "        LD A, (HL)\n"
    "        LD (PCLK), A    ; save new clock value\n"
    "\n"
    "        ; ------------------------------------------------------------------\n"
    "        ; 2.  TICK THE RNG  (Galois LFSR — 8-bit, XOR mask B8h)\n"
    "        ;     Polynomial x^8+x^6+x^5+x^4 gives maximal period 255.\n"
    "        ;     Run every frame so food placement varies with play rhythm.\n"
    "        ; ------------------------------------------------------------------\n"
    "        CALL RNGBYTE    ; advance LFSR one step; result stored in (RNG)\n"
    "\n"
    "        ; ------------------------------------------------------------------\n"
    "        ; 3.  READ KEYBOARD\n"
    "        ;     Port 38h returns the last key with bit 7 set as \"valid\" flag.\n"
    "        ;     Strip bit 7, check Ctrl-C, then convert case to uppercase so\n"
    "        ;     both lower and upper wasd work.\n"
    "        ; ------------------------------------------------------------------\n"
    "        IN A, (038H)\n"
    "        AND 07FH        ; strip bit 7 valid flag -> 7-bit ASCII\n"
    "        CP 03H          ; Ctrl-C (ASCII 3) ?\n"
    "        JP Z, EXIT      ; yes -> quit to monitor\n"
    "\n"
    "        AND 05FH        ; fold lowercase a-z to uppercase A-Z\n"
    "        LD (KEY), A     ; save for direction tests below\n"
    "\n"
    "        ; ------------------------------------------------------------------\n"
    "        ; 4.  UPDATE PENDING DIRECTION\n"
    "        ;     Pressing the key opposite to the current direction is silently\n"
    "        ;     ignored — the snake cannot reverse on itself.\n"
    "        ;     Opposite-direction check: direction D and its reverse share\n"
    "        ;     (D XOR 2) == reverse.  We test: if DIR == (new XOR 2) -> skip.\n"
    "        ; ------------------------------------------------------------------\n"
    "\n"
    "        ; ---- W -> UP (DUP=3) — blocked only when currently going DOWN ----\n"
    "        LD A, (KEY)\n"
    "        CP 57H          ; 'W'?\n"
    "        JR NZ, NOK_U\n"
    "        LD A, (DIR)\n"
    "        CP DDOWN        ; going DOWN is the opposite of UP\n"
    "        JR Z, NOK_U    ; can't turn 180 degrees -> ignore\n"
    "        LD A, DUP\n"
    "        LD (NDIR), A\n"
    "NOK_U:\n"
    "        ; ---- S -> DOWN (DDOWN=1) — blocked only when going UP ----\n"
    "        LD A, (KEY)\n"
    "        CP 53H          ; 'S'?\n"
    "        JR NZ, NOK_D\n"
    "        LD A, (DIR)\n"
    "        CP DUP\n"
    "        JR Z, NOK_D\n"
    "        LD A, DDOWN\n"
    "        LD (NDIR), A\n"
    "NOK_D:\n"
    "        ; ---- A -> LEFT (DLEFT=2) — blocked only when going RIGHT ----\n"
    "        LD A, (KEY)\n"
    "        CP 41H          ; 'A'?\n"
    "        JR NZ, NOK_L\n"
    "        LD A, (DIR)\n"
    "        CP DRIGHT\n"
    "        JR Z, NOK_L\n"
    "        LD A, DLEFT\n"
    "        LD (NDIR), A\n"
    "NOK_L:\n"
    "        ; ---- D -> RIGHT (DRIGHT=0) — blocked only when going LEFT ----\n"
    "        LD A, (KEY)\n"
    "        CP 44H          ; 'D'?\n"
    "        JR NZ, NOK_R\n"
    "        LD A, (DIR)\n"
    "        CP DLEFT\n"
    "        JR Z, NOK_R\n"
    "        LD A, DRIGHT\n"
    "        LD (NDIR), A\n"
    "NOK_R:\n"
    "\n"
    "        ; ------------------------------------------------------------------\n"
    "        ; 5.  SPEED THROTTLE  — move every 4th tick (~12.5 Hz)\n"
    "        ;     INC SPEED, test bits 1:0.  When both are zero (SPEED mod 4 == 0)\n"
    "        ;     we take a move step; otherwise loop back for the next tick.\n"
    "        ; ------------------------------------------------------------------\n"
    "        LD A, (SPEED)\n"
    "        INC A\n"
    "        LD (SPEED), A\n"
    "        AND 03H\n"
    "        JP NZ, LOOP     ; not a move tick -> back to clock wait\n"
    "\n"
    "        ; ------------------------------------------------------------------\n"
    "        ; 6.  COMMIT DIRECTION\n"
    "        ;     Apply the pending direction now that we are on a move tick.\n"
    "        ; ------------------------------------------------------------------\n"
    "        LD A, (NDIR)\n"
    "        LD (DIR), A\n"
    "\n"
    "        ; ------------------------------------------------------------------\n"
    "        ; 7.  FETCH CURRENT HEAD POSITION FROM SBUF[SHEAD]\n"
    "        ;     Address of SBUF[SHEAD].row  =  9000h + SHEAD*2\n"
    "        ;     With SHEAD in 0..63,  SHEAD*2 is 0..126 (fits in one byte),\n"
    "        ;     so the high byte of the address is always 90h.\n"
    "        ; ------------------------------------------------------------------\n"
    "        LD A, (SHEAD)\n"
    "        ADD A, A        ; A = SHEAD * 2  (no overflow: max 63*2 = 126)\n"
    "        LD L, A\n"
    "        LD H, 090H      ; HL = 9000h + SHEAD*2  =  &SBUF[SHEAD].row\n"
    "        LD B, (HL)      ; B = head row\n"
    "        INC HL\n"
    "        LD C, (HL)      ; C = head col\n"
    "\n"
    "        ; ------------------------------------------------------------------\n"
    "        ; 8.  LOOK UP DIRECTION DELTA  (drow, dcol) FROM DRTAB\n"
    "        ;     DRTAB holds 4 two-byte entries in direction order.\n"
    "        ; ------------------------------------------------------------------\n"
    "        LD A, (DIR)\n"
    "        ADD A, A        ; *2 (each entry is 2 bytes)\n"
    "        LD E, A\n"
    "        LD D, 0\n"
    "        LD HL, DRTAB\n"
    "        ADD HL, DE      ; HL = &DRTAB[DIR]\n"
    "        LD D, (HL)      ; D = drow  (00h = 0, 01h = +1, FFh = -1)\n"
    "        INC HL\n"
    "        LD E, (HL)      ; E = dcol\n"
    "\n"
    "        ; ------------------------------------------------------------------\n"
    "        ; 9.  COMPUTE NEW HEAD POSITION\n"
    "        ;     ADD A wraps mod 256; FFh (-1) + row works correctly because\n"
    "        ;     rows 1-22 never wrap below 0 (they hit the wall first).\n"
    "        ; ------------------------------------------------------------------\n"
    "        LD A, B\n"
    "        ADD A, D        ; new_row = head_row + drow\n"
    "        LD B, A\n"
    "        LD A, C\n"
    "        ADD A, E        ; new_col = head_col + dcol\n"
    "        LD C, A         ; B = new_row,  C = new_col\n"
    "\n"
    "        ; ------------------------------------------------------------------\n"
    "        ; 10. CHECK WHAT IS AT THE NEW CELL\n"
    "        ;     GETCHR preserves B and C (SCRADDR does not modify them).\n"
    "        ; ------------------------------------------------------------------\n"
    "        CALL GETCHR     ; A = screen byte at (B, C)\n"
    "\n"
    "        CP BLOCK\n"
    "        JP Z, GAMEOVER  ; hit wall (7Fh) or body segment -> GAME OVER\n"
    "\n"
    "        CP FOOD\n"
    "        JR Z, EATFOOD   ; food pellet -> grow\n"
    "\n"
    "        ; ------------------------------------------------------------------\n"
    "        ; 11. NORMAL MOVE — slide the snake one cell\n"
    "        ;     a) Erase the tail cell from the screen.\n"
    "        ;     b) Advance STAIL (tail segment leaves the ring buffer).\n"
    "        ;     c) Advance SHEAD, write new head position.\n"
    "        ;     d) Draw new head on screen.\n"
    "        ; ------------------------------------------------------------------\n"
    "\n"
    "        ; a) Erase tail: fetch SBUF[STAIL], write BLANK to screen\n"
    "        LD A, (STAIL)\n"
    "        ADD A, A        ; A = STAIL * 2\n"
    "        LD L, A\n"
    "        LD H, 090H      ; HL = &SBUF[STAIL].row\n"
    "        LD D, (HL)      ; D = tail row\n"
    "        INC HL\n"
    "        LD E, (HL)      ; E = tail col\n"
    "        ;    D, E clobbered by PUTCHR — save new head position (B,C) first\n"
    "        PUSH BC         ; preserve new head position across PUTCHR\n"
    "        LD B, D\n"
    "        LD C, E\n"
    "        LD A, BLANK\n"
    "        CALL PUTCHR     ; erase tail; B,C preserved by PUTCHR/SCRADDR\n"
    "        POP BC          ; restore new head position\n"
    "\n"
    "        ; b) Advance STAIL\n"
    "        LD A, (STAIL)\n"
    "        INC A\n"
    "        AND SMASK       ; mod 64\n"
    "        LD (STAIL), A\n"
    "\n"
    "        ; c) Advance SHEAD, write new head into ring buffer\n"
    "        LD A, (SHEAD)\n"
    "        INC A\n"
    "        AND SMASK\n"
    "        LD (SHEAD), A   ; store new SHEAD (A still holds new value)\n"
    "        ADD A, A        ; A = new SHEAD * 2\n"
    "        LD L, A\n"
    "        LD H, 090H      ; HL = &SBUF[new_SHEAD].row\n"
    "        LD (HL), B      ; .row = new head row\n"
    "        INC HL\n"
    "        LD (HL), C      ; .col = new head col\n"
    "\n"
    "        ; d) Draw new head\n"
    "        LD A, BLOCK\n"
    "        CALL PUTCHR     ; B = new_row,  C = new_col\n"
    "\n"
    "        JP LOOP\n"
    "\n"
    "; =============================================================================\n"
    "; EATFOOD — snake eats the food pellet at (B, C)\n"
    ";\n"
    "; The tail is NOT erased — the snake grows by one segment.\n"
    "; =============================================================================\n"
    "EATFOOD:\n"
    "        ; Advance SHEAD and write new head (the food cell) into ring buffer\n"
    "        LD A, (SHEAD)\n"
    "        INC A\n"
    "        AND SMASK\n"
    "        LD (SHEAD), A   ; A = new SHEAD index\n"
    "        ADD A, A\n"
    "        LD L, A\n"
    "        LD H, 090H\n"
    "        LD (HL), B      ; SBUF[new_SHEAD].row = new head row\n"
    "        INC HL\n"
    "        LD (HL), C      ; SBUF[new_SHEAD].col = new head col\n"
    "\n"
    "        ; Draw new head (overwrites the food pellet character)\n"
    "        LD A, BLOCK\n"
    "        CALL PUTCHR\n"
    "\n"
    "        ; Place a new food pellet somewhere in the play field\n"
    "        CALL PLACEFOOD\n"
    "\n"
    "        JP LOOP\n"
    "\n"
    "; =============================================================================\n"
    "; GAME OVER — display the frozen board for ~2 seconds, then return\n"
    "; =============================================================================\n"
    "GAMEOVER:\n"
    "        ; Wait 100 ticks (~2 seconds at 50 Hz) so the player sees the\n"
    "        ; frozen board, then restart from the beginning.\n"
    "        LD D, 100\n"
    "GOWAIT: LD HL, CLKLO\n"
    "GOWLP:  LD A, (PCLK)\n"
    "        CP (HL)\n"
    "        JR Z, GOWLP\n"
    "        LD A, (HL)\n"
    "        LD (PCLK), A\n"
    "        DEC D\n"
    "        JR NZ, GOWAIT\n"
    "        JP START        ; reinitialise and play again\n"
    "\n"
    "; =============================================================================\n"
    "; EXIT — Ctrl-C: re-enable interrupts and return to the monitor\n"
    "; =============================================================================\n"
    "EXIT:\n"
    "        EI\n"
    "        RET\n"
    "\n"
    "; =============================================================================\n"
    "; INITSCR — initialise the screen for a new game\n"
    ";\n"
    "; 1. Write GFXMK (97h) into column 0 of every row.\n"
    "; 2. Clear columns 1-39 of every row to BLANK.\n"
    "; 3. Fill top wall    (row 0,  cols 1-39) with BLOCK.\n"
    "; 4. Fill bottom wall (row 23, cols 1-39) with BLOCK.\n"
    "; 5. Fill left wall   (rows 1-22, col 1)  with BLOCK.\n"
    "; 6. Fill right wall  (rows 1-22, col 39) with BLOCK.\n"
    ";\n"
    "; Registers: A, B, C, D, E, H, L all clobbered.\n"
    "; =============================================================================\n"
    "INITSCR:\n"
    "        ; ---- Steps 1+2: write GFXMK to col 0, BLANK to cols 1-39 ----\n"
    "        LD B, 24        ; row counter — 24 rows total\n"
    "        LD HL, ROWTAB   ; pointer into the row-address table\n"
    "ILUP:\n"
    "        ; Load row start address from ROWTAB (little-endian 16-bit word)\n"
    "        LD E, (HL)\n"
    "        INC HL\n"
    "        LD D, (HL)\n"
    "        INC HL\n"
    "        PUSH BC         ; save outer row counter (B)\n"
    "        PUSH HL         ; save ROWTAB pointer\n"
    "        EX DE, HL       ; HL = row start address in screen RAM\n"
    "        LD (HL), GFXMK  ; col 0 = 97h (graphics mode marker)\n"
    "        INC HL          ; advance to col 1\n"
    "        LD B, 39        ; 39 remaining columns (1-39)\n"
    "ICLR:   LD (HL), BLANK\n"
    "        INC HL\n"
    "        DJNZ ICLR\n"
    "        POP HL          ; restore ROWTAB pointer\n"
    "        POP BC          ; restore row counter\n"
    "        DJNZ ILUP\n"
    "\n"
    "        ; ---- Step 3: top wall (row 0, cols 1-39) ----\n"
    "        LD B, 0\n"
    "        LD C, 1\n"
    "        LD D, 39        ; 39 cells\n"
    "ITOP:   LD A, BLOCK\n"
    "        PUSH DE         ; D clobbered by SCRADDR inside PUTCHR\n"
    "        CALL PUTCHR     ; B, C preserved; D, E, H, L clobbered\n"
    "        POP DE\n"
    "        INC C\n"
    "        DEC D\n"
    "        JR NZ, ITOP\n"
    "\n"
    "        ; ---- Step 4: bottom wall (row 23, cols 1-39) ----\n"
    "        LD B, 23\n"
    "        LD C, 1\n"
    "        LD D, 39\n"
    "IBOT:   LD A, BLOCK\n"
    "        PUSH DE\n"
    "        CALL PUTCHR\n"
    "        POP DE\n"
    "        INC C\n"
    "        DEC D\n"
    "        JR NZ, IBOT\n"
    "\n"
    "        ; ---- Step 5: left wall (rows 1-22, col 1) ----\n"
    "        LD B, 1\n"
    "        LD C, 1\n"
    "        LD D, 22        ; 22 cells\n"
    "ILFT:   LD A, BLOCK\n"
    "        PUSH DE\n"
    "        CALL PUTCHR\n"
    "        POP DE\n"
    "        INC B\n"
    "        DEC D\n"
    "        JR NZ, ILFT\n"
    "\n"
    "        ; ---- Step 6: right wall (rows 1-22, col 39) ----\n"
    "        LD B, 1\n"
    "        LD C, 39\n"
    "        LD D, 22\n"
    "IRGT:   LD A, BLOCK\n"
    "        PUSH DE\n"
    "        CALL PUTCHR\n"
    "        POP DE\n"
    "        INC B\n"
    "        DEC D\n"
    "        JR NZ, IRGT\n"
    "\n"
    "        RET\n"
    "\n"
    "; =============================================================================\n"
    "; PLACEFOOD — place a FOOD pellet at a random empty cell in the play area\n"
    ";\n"
    "; Uses RNGBYTE to generate row and column independently (two fresh LFSR steps\n"
    "; each) so they do not share carry-flag contamination.  Tries up to 64\n"
    "; positions; gives up silently if all are occupied (play field nearly full).\n"
    ";\n"
    "; PFROW and PFCOL hold the candidate position across the GETCHR call\n"
    "; (GETCHR clobbers D, E, H, L but not these memory locations).\n"
    "; =============================================================================\n"
    "PLACEFOOD:\n"
    "        LD B, 64        ; attempt counter for DJNZ\n"
    "PFLOOP:\n"
    "        PUSH BC         ; save attempt counter\n"
    "\n"
    "        ; ---- Two RNG steps for the row (fresh, independent value) ----\n"
    "        CALL RNGBYTE    ; step 1\n"
    "        CALL RNGBYTE    ; step 2 — A = new RNG value\n"
    "\n"
    "        ; Map to row 1-22: use lower 5 bits (0-31), fold 22-31 -> 0-9, add 1\n"
    "        AND 01FH\n"
    "        CP 22\n"
    "        JR C, PFROW_OK\n"
    "        SUB 22\n"
    "PFROW_OK:\n"
    "        INC A\n"
    "        LD (PFROW), A\n"
    "\n"
    "        ; ---- Two more RNG steps for the column (separate from row) ----\n"
    "        CALL RNGBYTE\n"
    "        CALL RNGBYTE    ; A = new RNG value\n"
    "\n"
    "        ; Map to col 2-38: use lower 6 bits (0-63), fold 37-63 -> 0-26, add 2\n"
    "        AND 03FH\n"
    "        CP 37\n"
    "        JR C, PFCOL_OK\n"
    "        SUB 37\n"
    "PFCOL_OK:\n"
    "        ADD A, 2\n"
    "        LD (PFCOL), A\n"
    "\n"
    "        ; ---- Check whether that screen cell is empty ----\n"
    "        LD A, (PFROW)\n"
    "        LD B, A\n"
    "        LD A, (PFCOL)\n"
    "        LD C, A\n"
    "        CALL GETCHR     ; A = screen byte;  B, C preserved;  D, E, H, L clobbered\n"
    "        POP BC          ; restore attempt counter\n"
    "\n"
    "        CP BLANK\n"
    "        JR NZ, PFNEXT  ; occupied -> try again\n"
    "\n"
    "        ; ---- Empty: place food here ----\n"
    "        LD A, (PFROW)\n"
    "        LD B, A\n"
    "        LD A, (PFCOL)\n"
    "        LD C, A\n"
    "        LD A, FOOD\n"
    "        CALL PUTCHR\n"
    "        RET\n"
    "\n"
    "PFNEXT:\n"
    "        DJNZ PFLOOP\n"
    "        RET             ; all attempts failed — give up\n"
    "\n"
    "; =============================================================================\n"
    "; RNGBYTE — advance the Galois LFSR by one step and return the new value in A\n"
    ";\n"
    "; XOR mask: B8h = 10111000b  (polynomial x^8+x^6+x^5+x^4, period 255)\n"
    "; The state 00h is invalid for a Galois LFSR and is avoided by the seed guard\n"
    "; in START.\n"
    "; =============================================================================\n"
    "RNGBYTE:\n"
    "        LD A, (RNG)\n"
    "        RRCA            ; shift right; LSB -> carry\n"
    "        JR NC, RNGB1    ; if LSB was 0, no feedback needed\n"
    "        XOR 0B8H        ; LSB was 1: apply feedback taps\n"
    "RNGB1:  LD (RNG), A\n"
    "        RET\n"
    "\n"
    "; =============================================================================\n"
    "; GETCHR — read one character from screen RAM\n"
    ";\n"
    "; Entry:  B = row (0-23),  C = col (0-39)\n"
    "; Exit:   A = screen byte at that position;  B, C preserved\n"
    "; =============================================================================\n"
    "GETCHR:\n"
    "        CALL SCRADDR    ; HL = screen address;  A, D, E, H, L clobbered;  B, C preserved\n"
    "        LD A, (HL)\n"
    "        RET\n"
    "\n"
    "; =============================================================================\n"
    "; PUTCHR — write one character to screen RAM\n"
    ";\n"
    "; Entry:  B = row (0-23),  C = col (0-39),  A = byte to write\n"
    "; Exit:   character written;  B, C preserved;  HL = screen address\n"
    "; =============================================================================\n"
    "PUTCHR:\n"
    "        PUSH AF         ; save character and flags\n"
    "        CALL SCRADDR    ; HL = screen address;  B, C preserved\n"
    "        POP AF          ; restore character\n"
    "        LD (HL), A      ; write it\n"
    "        RET\n"
    "\n"
    "; =============================================================================\n"
    "; SCRADDR — convert (row, col) to a screen-RAM address\n"
    ";\n"
    "; Entry:  B = row (0-23),  C = col (0-39)\n"
    "; Exit:   HL = screen-RAM address;  B, C preserved\n"
    ";         A, D, E clobbered\n"
    ";\n"
    "; The ABC80 video RAM (7C00h-7FFFh) is interleaved across three 8-row banks\n"
    "; with a stride of 80h (128) bytes between rows and 28h (40) bytes between\n"
    "; banks.  ROWTAB at the bottom of this file holds the 24 row start addresses\n"
    "; as little-endian 16-bit words; we index it as ROWTAB[row*2].\n"
    ";\n"
    "; NOTE: uses ADD A,A (not RLCA) so the result is independent of the carry flag.\n"
    "; =============================================================================\n"
    "SCRADDR:\n"
    "        LD HL, ROWTAB   ; base of the row-address table\n"
    "        LD A, B         ; A = row (0-23)\n"
    "        ADD A, A        ; A = row * 2  (max 23*2 = 46, no overflow)\n"
    "        LD D, 0\n"
    "        LD E, A\n"
    "        ADD HL, DE      ; HL -> ROWTAB entry for this row\n"
    "        LD A, (HL)\n"
    "        INC HL\n"
    "        LD H, (HL)\n"
    "        LD L, A         ; HL = row start address (loaded little-endian)\n"
    "        LD D, 0\n"
    "        LD E, C\n"
    "        ADD HL, DE      ; HL = rowstart + col  =  screen address\n"
    "        RET\n"
    "\n"
    "; =============================================================================\n"
    "; DRTAB — direction delta table\n"
    ";\n"
    "; Four entries in direction-code order (DRIGHT=0, DDOWN=1, DLEFT=2, DUP=3).\n"
    "; Each entry is two bytes: (drow, dcol).\n"
    "; FFh represents -1 using Z80 signed byte / modulo-256 arithmetic.\n"
    "; =============================================================================\n"
    "DRTAB:\n"
    "        DEFB 0,    1    ; DRIGHT: drow=0,  dcol=+1\n"
    "        DEFB 1,    0    ; DDOWN:  drow=+1, dcol=0\n"
    "        DEFB 0,  0FFH   ; DLEFT:  drow=0,  dcol=-1\n"
    "        DEFB 0FFH, 0    ; DUP:    drow=-1, dcol=0\n"
    "\n"
    "; =============================================================================\n"
    "; ROWTAB — screen-RAM start address for each of the 24 rows (little-endian)\n"
    ";\n"
    "; The ABC80 video RAM layout:\n"
    ";   Bank 0 (rows  0- 7): 7C00h, 7C80h, 7D00h, 7D80h, 7E00h, 7E80h, 7F00h, 7F80h\n"
    ";   Bank 1 (rows  8-15): 7C28h, 7CA8h, 7D28h, 7DA8h, 7E28h, 7EA8h, 7F28h, 7FA8h\n"
    ";   Bank 2 (rows 16-23): 7C50h, 7CD0h, 7D50h, 7DD0h, 7E50h, 7ED0h, 7F50h, 7FD0h\n"
    ";\n"
    "; Row stride = 80h (128 bytes).  Bank offset = 28h (40 bytes = one row width).\n"
    "; =============================================================================\n"
    "ROWTAB:\n"
    "        DW 07C00H       ; row  0\n"
    "        DW 07C80H       ; row  1\n"
    "        DW 07D00H       ; row  2\n"
    "        DW 07D80H       ; row  3\n"
    "        DW 07E00H       ; row  4\n"
    "        DW 07E80H       ; row  5\n"
    "        DW 07F00H       ; row  6\n"
    "        DW 07F80H       ; row  7\n"
    "        DW 07C28H       ; row  8\n"
    "        DW 07CA8H       ; row  9\n"
    "        DW 07D28H       ; row 10\n"
    "        DW 07DA8H       ; row 11\n"
    "        DW 07E28H       ; row 12\n"
    "        DW 07EA8H       ; row 13\n"
    "        DW 07F28H       ; row 14\n"
    "        DW 07FA8H       ; row 15\n"
    "        DW 07C50H       ; row 16\n"
    "        DW 07CD0H       ; row 17\n"
    "        DW 07D50H       ; row 18\n"
    "        DW 07DD0H       ; row 19\n"
    "        DW 07E50H       ; row 20\n"
    "        DW 07ED0H       ; row 21\n"
    "        DW 07F50H       ; row 22\n"
    "        DW 07FD0H       ; row 23\n"
    ;
